const words = { 
	'11.01.2016' : {
		's ' : 'z', 
		'v ' : 'f', 
		'w ' : 'v', 
		'h ' : 'ø', 
		'ch ' : 'h', 
		'sch ' : 'sh', 
		'st ' : 'sht (samo na pocetku reci)', 
		'sp ' : 'shp (samo na pocetku reci)', 
		'ß ' : 's', 
		'ei ' : 'aj', 
		'ie ' : 'i (dugo)', 
		'eu ' : 'oj', 
		'ä ' : 'usta za "a" a izgovaramo "e"', 
		'ö ' : 'usta za "o" a izgovaramo "e"', 
		'ü ' : 'usta za "u" a izgovaramo "i"', 
		'-ig ' : 'ih', 
		'tsch ' : 'ch', 
		'äu ' : 'oj', 
		'machen ' : 'ciniti, raditi', 
		'arbeiten ' : 'raditi', 
		'heißen ' : 'zvati se', 
		'essen ' : 'jesti', 
		'lessen ' : 'citati', 
		'fahren ' : 'voziti', 
		'laufen ' : 'trcati, setati', 
		'sein ' : 'biti', 
		'sagen ' : 'reci, kazati', 
		'ordnen ' : 'rasporediti', 
		'(Herzlich) Willkommen ' : '(Srdacno) Dobrodosli', 
		'bitte ' : 'molim', 
		'Freut mich ' : 'drago mi je', 
	},
	'14.01.2016' : {
		'die Stadt ' : 'grad', 
		'die Hauptstadt ' : 'glavni grad', 
		'der Unterschied ' : 'razlika', 
		'der Schüler ' : 'djak', 
		'der Lerner ' : 'ucenik', 
		'der Stadtführer ' : 'gradski vodic', 
		'der Spaß ' : 'zabava', 
		'die Straße ' : 'ulica', 
		'das Gegenteil ' : 'suprotnost', 
		'lesen ' : 'citati', 
		'schreiben ' : 'pisati', 
		'der Gegenstand ' : 'predmet (fizicki)', 
		'Wer ' : 'ko?', 
		'Was ' : 'sta?', 
		'Wo ' : 'gde?', 
		'Woher ' : 'odakle?', 
		'Wohin ' : 'kuda?', 
		'Wann ' : 'kada?', 
		'Wie ' : 'kako?', 
		'drehen ' : 'listati', 
		'ergänzen ' : 'dopuniti', 
		'Satzzeichen ' : '? , . ; :', 
		'der Wasserhahn ' : 'cesma', 
		'lernen ' : 'uciti', 
		'lehren ' : 'poducavati', 
		'überspringen ' : 'preskociti', 
		'springen ' : 'skociti', 
		'das Gespräch ' : 'razgovor', 
		'unbekannte ' : 'nepoznato', 
		'Buchstaben ' : 'slovo', 
		'bedeuten ' : 'znaciti', 
		'Entschuldigung ' : 'izvinite', 
		'buchstabieren ' : 'spelovati', 
		'da ' : 'tu (mesto)', 
		'Vorname ' : 'Name', 
		'Familienname ' : 'Nachname', 
		'Land ' : 'zemlja (tlo)', 
		'die Folge ' : 'epizoda', 
		'das Bild ' : 'slika', 
		'bereit ' : 'spreman', 
		'meinen ' : 'misliti (stav)', 
		'hübsch ' : 'lepa (najcesce za zene)', 
		'schön ' : 'hübsch', 
		'wohnen ' : 'stanovati', 
		'leben ' : 'ziveti', 
		'der Tee ' : 'caj', 
		'der Kaffee ' : 'kafa', 
		'der Moment ' : 'trenutak', 
		'die Eltern ' : 'roditelji', 
		'die Mutter ' : 'majka', 
		'der Vater ' : 'otac', 
		'die Großmutter ' : 'baka', 
		'die Schwester ' : 'sestra', 
		'der Bruder ' : 'brat', 
		'die Geschwister ' : 'eng. siblings (brat i sestra, brat i brat, sestra i sestra)', 
		'groß ' : 'veliko', 
		'klein ' : 'malo', 
		'die Übung ' : 'vezba', 
		'sagen ' : 'reci, kazati', 
		'hier ' : 'ovde', 
		'da ' : 'tu', 
		'dort ' : 'tamo', 
		'Ihnen ' : 'Vama', 
		'Dir ' : 'tebi', 
		'müde ' : 'umoran', 
		'erholten ' : 'odmoran', 
	},
	'15.01.2016' : {
		'öffnen ' : 'otvoriti', 
		'offen ' : 'otvoren', 
		'der Abschnitt ' : 'sekcija, odsek', 
		'das Kind ' : 'dete', 
		'der Lehrer ' : 'ucitelj', 
		'der Lerner ' : 'ucenik', 
		'der Sohn / die Söhne ' : 'sin / sinovi', 
		'die Tochter ' : 'kcerka', 
		'das Rätsel ' : 'zagonetka', 
		'die Zahlen ' : 'brojevi', 
		'die Zahl ' : 'broj', 
		'zahlen ' : 'platiti', 
		'die Nummer ' : 'broj', 
		'bezahlen ' : 'platiti (odmah)', 
		'die Lösung ' : 'resenje', 
		'Liegen ' : 'lezati', 
		'verheiratet ' : 'vencan / a', 
		'geschieden ' : 'razveden / a', 
		'haben ' : 'imati', 
		'alt ' : 'staro', 
		'jung ' : 'mlado', 
		'die Heimatland ' : 'domovina, zemlja porekla', 
		'der Ort ' : 'mesto', 
		'der Wohnort ' : 'prebivaliste', 
		'Familienstand ' : 'bracno stanje', 
		'ledig ' : 'neozenjen, posle 18g (eng. single)', 
		'verwitwet ' : 'udovac / ica', 
		'die Witwe ' : 'udovica', 
		'der Witwer ' : 'udovac', 
		'der Herr ' : 'gospodin', 
		'die Frau ' : 'gospodja', 
		'der Titel ' : 'naslov', 
		'Sich vorstellen ' : 'predstaviti se', 
		'viele ' : 'mnogo', 
		'das Baby ' : 'beba', 
		'der Freund ' : 'prijatelj', 
		'die Freundin ' : 'prijateljica', 
		'leider ' : 'nazalost', 
		'es tut mir leid ' : 'zao mi je', 
		'König ' : 'kralj', 
	},
	'18.01.2016' : {
		'lang ' : 'dugo', 
		'kurz ' : 'kratko', 
		'gegenteil ' : 'suprotnost', 
		'die Seite ' : 'strana', 
		'passen ' : 'biti taman', 
		'zeigen ' : 'pokazati', 
		'an kreuzen ' : 'obeleziti, markirati', 
		'auf füllen ' : 'popuniti', 
		'der Mensch / -en (pl) ' : 'covek, ljudi (pl)', 
		'der Apfel ' : 'jabuka', 
		'die Erde ' : 'zemlja (zemljiste, materijal)', 
		'der Markt ' : 'pijaca', 
		'folgen ' : 'pratiti', 
		'die Folge ' : 'epizoda', 
		'brauchen ' : 'potreban ( eng. need )', 
		'das Problem ' : 'problem', 
		'wie viel? ' : 'koliko?', 
		'das Kilo ' : 'kilo', 
		'das Obst ' : 'voce', 
		'junger Mann ' : 'mladic', 
		'sonst noch etwas ' : 'inace jos nesto', 
		'sonst ' : 'inace', 
		'noch ' : 'jos', 
		'etwas ' : 'nesto', 
		'vielleicht ' : 'mozda', 
		'kosten ' : 'kostati', 
		'die Kosten ' : 'troskovi', 
		'gern(e) ' : 'rado', 
		'das Wort / - en ' : 'rec', 
		'die Wörten ' : 'reci', 
		'das Lebensmittel ' : 'namirnice', 
		'Nennen ' : 'imenovati', 
		'das Brötchen ' : 'kifla, zemicka, pecivo', 
		'bisschen ' : 'ugriz', 
		'der Biss ' : 'ujed, ugriz, zalogaj', 
		'schauen ' : 'gledati', 
		'sehen ' : 'videti', 
		'der Kuchen ' : 'kolac', 
		'die Tomate ' : 'paradajz', 
		'der Ort / -e (pl) ' : 'mesto', 
		'der Korb / -e (pl) ' : 'korpa', 
		'im ' : 'unutra', 
		'der Fisch / -e (pl) ' : 'riba', 
		'die Traube / -en (pl) ' : 'grozdje', 
		'der Saft / -e (pl) ' : 'sok', 
		'die Säfte ' : 'sokovi', 
		'drehen ' : 'okrenuti', 
		'der Zettel ' : 'cedulja', 
		'alles ' : 'sve', 
		'nichts ' : 'nista', 
		'der Sahne ' : 'slag', 
		'die Brille ' : 'naocare', 
		'die Birne ' : 'kruska', 
		'vergleichen ' : 'porediti', 
		'gleich ' : 'isto (eng. same)', 
		'das Beispiel ' : 'primer', 
		'die Anmeldung ' : 'prijava', 
	},
	'21.01.2016' : {
		'das Gewicht ' : 'masa', 
		'die Maß ' : 'mera', 
		'die Maßeinheiten ' : 'merna jedinica', 
		'die Einheit ' : 'jedinica (u bilo kom obliku)', 
		'die Abteilung ' : 'odeljak, odsek', 
		'das Angebote ' : 'ponuda', 
		'sonder ' : 'specijalna, posebna', 
		'oben ' : 'gore', 
		'unten ' : 'dole', 
		'mitte ' : 'u sredini', 
		'links ' : 'levo', 
		'rechts ' : 'desno', 
		'die Null ' : 'nula', 
		'komma ' : 'zarez', 
		'das Öl ' : 'ulje', 
		'die Flasche ' : 'boca, flasa', 
		'die Packung ' : 'pakovanje', 
		'das Rind ' : 'govece', 
		'die Kuh ' : 'krava', 
		'der Bulle / der Stier ' : 'vo, bik', 
		'die Rindfleich ' : 'govedina', 
		'die Dose ' : 'konzerva', 
		'die Dosis ' : 'mera (leka)', 
		'der Becher ' : 'mala posuda, iskljucivo od plastike (casa za jogurt, ...)', 
		'essen ' : 'jesti', 
		'das Esse ' : 'jelo', 
		'lieblings ' : 'omiljeni', 
		'der Liebling ' : 'miljenik', 
		'der Film ' : 'film', 
		'die Soße ' : 'sos', 
		'das Hähnchen ' : 'piletina', 
		'der Durst ' : 'zedan', 
		'der Hunger ' : 'gladan', 
		'mögen ' : 'svidjati, gotiviti (eng. like)', 
		'lieben ' : 'voleti (strastveno)', 
		'schmecken ' : 'osecati ukus', 
		'der Geschmack ' : 'ukus (generano)', 
		'Vorsicht! ' : 'pazi', 
		'die Vorsicht ' : 'paznja, obazrivost', 
		'vorsichtig ' : 'obazriv', 
		'das Zimmer ' : 'prostorija, soba', 
		'Wohnzimmer ' : 'dnevna soba', 
		'der Stock ' : 'sprat', 
		'die Möbel (pl) ' : 'namestaj', 
		'das Möbelstück ' : 'komad namestaja', 
		'der Schritt ' : 'korak', 
		'die Schritte ' : 'koracati', 
		'kennen ' : 'poznavati ( mesto ili vestina )', 
		'weiter ' : 'dalje', 
		'teuer ' : 'skupo', 
		'billig ' : 'jeftino', 
		'der Einfall ' : 'dosetka, ideja', 
		'die Idee ' : 'ideja (internacionalno)', 
		'machen ' : 'ciniti, raditi', 
		'noch ' : 'jos', 
		'unmöglich ' : 'nemoguce', 
		'gerfallen ' : 'dopadati se (gotiviti)', 
		'finden ' : 'naci (gotiviti)', 
		'gut ' : 'dobro', 
		'schlecht ' : 'lose (kvalitet)', 
		'schlimm ' : 'lose (situacija)', 
		'böse    ' : 'zlo, lose (moralno, eticki)', 
		'verrückt ' : 'iscasen, poremecen', 
		'seltsam ' : 'neobicno, cudno', 
		'höflich ' : 'ljubazan, uctiv', 
		'freundlich ' : 'prijatan', 
		'der Flur ' : 'hodnik', 
	},
	'22.01.2016' : {
		'laut ' : 'glasno', 
		'leise ' : 'tiho', 
		'wirklich ' : 'stvarno, zaista', 
		'das Haus ' : 'kuca', 
		'breit ' : 'siroko', 
		'schmal ' : 'usko', 
		'schön ' : 'lepo', 
		'hässlich ' : 'ruzno', 
		'hell ' : 'svetlo', 
		'dunkel ' : 'tamno', 
		'zwichen ' : 'izmedju, medju', 
		'vergleichen ' : 'uporediti', 
		'das Ratespiel ' : 'igra pogadjanja', 
		'aber ' : 'vrlo, veoma, bas, ali', 
		'die Dusche ' : 'tus', 
		'das Bett ' : 'krevet', 
		'das Wasschbecken ' : 'lavabo', 
		'der Schrank ' : 'ormar', 
		'der Kühlschrank ' : 'frizider', 
		'der Herd ' : 'sporet, rerna', 
		'die Badewanne ' : 'kada', 
		'der Fernseher ' : 'televizor', 
		'die Spühle ' : 'sudopera', 
		'das Gerät ' : 'uredjaj, stroj, masina', 
		'grün ' : 'zelena', 
		'gelb ' : 'zuta', 
		'grau ' : 'siva', 
		'anzeigen ' : 'oglasi', 
		'der Preis ' : 'cena, nagrada', 
		'preiswert ' : 'jeftin', 
		'mieten ' : 'onaj koji zakupljuje (stanar)', 
		'vermieten ' : 'onaj koji daje u najam (vlasnik)', 
		'die Miete ' : 'izdavati', 
		'das Praktikum ' : 'praksa', 
		'die Praxis ' : 'ordinacija', 
		'möbliert ' : 'namesten', 
		'die Zeit ' : 'vreme (u kontekstu sata)', 
		'das Wetter ' : 'vreme (u kontekstu vremenske prognoze)', 
		'voll ' : 'puno', 
		'leer ' : 'prazno', 
		'der Raum ' : 'prostor', 
		'die Lage ' : 'stanje, leziste, situirano', 
		'die Woche ' : 'sedmica', 
		'ruhig ' : 'mirno', 
		'die Ruhe ' : 'mir (spokoj)', 
		'neben ' : 'pored (uopsteno)', 
		'Nebenkosten ' : 'sporedni troskovi', 
		'sitzt ' : 'sedeti', 
		'jetzt ' : 'sada', 
		'sofort ' : 'odmah', 
		'dringend ' : 'hitno, vazno', 
		'warm ' : 'toplo', 
		'kalt ' : 'hladno', 
		'die Ferien ' : 'raspust', 
		'der Urlaub ' : 'odmor', 
		'der Stern ' : 'zvezda', 
		'das Zeichen ' : 'znak', 
		'glauben ' : 'verovati', 
		'antworten ' : 'odgovoriti (usmeno, pismeno,...)', 
		'helfen ' : 'pomoci', 
		'möchten ' : 'zeleti (eng. wish)', 
		'Sternzeichen ' : 'horoskop', 
		'an ' : 'na (predlog)', 
	},
	'25.01.2016' : {
		'Steinbock ' : 'jarac', 
		'gemütliches ' : 'udobno', 
		'vor allem ' : 'pre svega', 
		'knallrotes ' : 'drecavo crvena', 
		'besonders gern ' : 'posebno drago/draga', 
		'Welche ' : 'koja, koji', 
		'lecker ' : 'ukusno', 
		'einrichten ' : 'uredjen', 
		'der Knall ' : 'eksplozija', 
		'der Wunsch ' : 'zelja (u bukvalnom smislu)', 
		'wünschen ' : 'zeleti', 
		'die Gemütlichkeit ' : 'udobno', 
		'das Herz ' : 'srce', 
		'der Bahnhof ' : 'zeleznicka stanica', 
		'der Stift ' : 'pisljka (olovka)', 
		'der Shal ' : 'sal', 
		'die Jacke ' : 'jakna', 
		'schon ' : 'vec, bas', 
		'der Tag ' : 'dan', 
		'genug ' : 'dovoljno, dosta', 
		'die Sprache ' : 'jezik', 
		'sprechen ' : 'pricati', 
		'aufstehen ' : 'ustati', 
		'aufräumen ' : 'pospremiti', 
		'stimmt ' : 'tako je', 
		'einkaufen ' : 'kupovati', 
		'kaufen ' : 'kupiti', 
		'kochen ' : 'kuvati', 
		'frühstücken ' : 'doruckovati', 
		'das Frühstück ' : 'dorucak', 
		'fernsehen ' : 'gledati televiziju', 
		'der Fernseher ' : 'televizor', 
		'lustig ' : 'smesno', 
		'ernst ' : 'ozbiljno', 
		'traurig ' : 'tuzno', 
		'langweilig ' : 'dosadan', 
		'doof ' : 'simpaticno glupo', 
		'dumm ' : 'neutralno glupo', 
		'blöd ' : 'glup (uvredljivo)', 
		'nett ' : 'fino, ljubazno (eng. nice)', 
		'lachen ' : 'smejati se', 
		'geben ' : 'dati, postojati ... (e -> i)', 
		'spät ' : 'kasno', 
		'früh ' : 'rano', 
		'der Zeiger ' : 'kazaljka', 
		'der Vollidiot ' : 'potpuni idiot', 
		'die Uhr ' : 'sat (masina, rucni sat, ... eng. watch)', 
		'die Stunde ' : 'cas (60 min ... eng. hour)', 
		'vorspielen ' : 'odsvirati', 
		'verbinden ' : 'povezati', 
		'zu spät kommen ' : 'zakasniti', 
	},
	'28.01.2016' : {
		'aufräumen ' : 'pospremiti', 
		'anrufen ' : 'pozvati (telefonom)', 
		'aufstehen ' : 'ustati', 
		'stehen ' : 'stajati', 
		'fernsehen ' : 'gledati tv', 
		'drehen ' : 'okretati', 
		'umdrehen ' : 'okrenuti (jednom)', 
		'die Sonne ' : 'sunce', 
		'der Mittag ' : 'podne', 
		'der Vormittag ' : 'pre podne', 
		'der Nachmittag ' : 'posle podne', 
		'der Morgen ' : 'jutro, sutra', 
		'heute ' : 'danas', 
		'der Abend ' : 'vece', 
		'die Nacht ' : 'noc', 
		'am ' : '(eng. in)', 
		'in der Nacht ' : 'tokom noci', 
		'von ' : 'od', 
		'bis ' : 'do', 
		'am ' : 'dane u sedmici i/ili doba dana', 
		'um ' : 'kod satnice', 
		'die Schicht ' : 'smena, sloj', 
		'jeden Tag ' : 'svakog dana', 
		'jeden ' : 'svaki', 
		'jede ' : 'savi', 
		'Öffnungszeit / -en ' : 'radno vreme', 
		'der Depp ' : 'debil od milosti', 
		'das Joggen ' : 'dzogiranje', 
		'zwei mal ' : 'dva puta', 
		'mal ' : 'puta (npr. koliko puta)', 
		'traiben ' : 'terati (osobu, stoku)', 
		'Sport treiben ' : 'baviti se sportom', 
		'fechten ' : 'macevanje', 
		'auch ' : 'isto, takodje', 
		'mitkommen ' : 'doci sa nekim', 
		'der Wetter ' : 'vreme', 
		'regnen ' : 'pada kisa', 
		'der Regen ' : 'kisa', 
		'scheinen ' : 'sijati, ciniti se', 
		'die Lust ' : 'volja', 
		'Lust haben ' : 'imati volju, biti u fazonu', 
		'das Schloss ' : 'zamak, brava (mehanizam)', 
		'der Schuh/ -e ' : 'obuca, cipela', 
		'der Anzug/ - ˚˚ e ' : 'odeca, odelo', 
		'das Geld ' : 'novac', 
		'Mach nicht ' : 'nema veze', 
		'schnell ' : 'brzo', 
		'langsam ' : 'sporo', 
		'öft ' : 'ucestalo', 
		'selten ' : 'retko', 
	},
	'29.01.2016' : {
		'aufrufen ' : 'prozvati', 
		'anrufen ' : 'pozvati (telefonom)', 
		'weitermachten ' : 'nastaviti (dalje sa radom)', 
		'der Laden ' : 'radnja', 
		'das Geschäft ' : 'eng. bussiness', 
		'vielleicht ' : 'mozda', 
		'der Quatsch ' : 'besmislica (eng. nonesense)', 
		'der Obstladen ' : 'prodavnica voca', 
		'der Wind ' : 'vetar', 
		'windig ' : 'vetrovito', 
		'warm ' : 'toplo', 
		'kalt ' : 'hladno', 
		'schneien ' : 'snezi, pada sneg', 
		'der Schnee ' : 'sneg', 
		'bewölkt ' : 'oblacno', 
		'die Wolke ' : 'oblak', 
		'Norden ' : 'sever', 
		'Süden  ' : 'jug', 
		'Westen ' : 'zapad', 
		'Osten  ' : 'istok', 
		'das Kraut ' : 'biljka', 
		'die Jahreszeiten ' : 'godisnja doba', 
		'der Satz / -˚˚e ' : 'recenica', 
		'gucken ' : 'gledaj, baci pogled', 
		'nehmen ' : 'uzimati ... ( e -> i )', 
		'heiß ' : 'vrelo (vruce)', 
		'dabai haben ' : 'imati sa sobom nesto', 
		'Gesundheit ' : 'ziv bio, zdrav bio', 
		'doch ' : 'potvrdan odgovor na negativno pitanje (jedno od znacnja)', 
		'möchten ' : 'zeleti', 
	},
	'01.02.2016' : {
		'gar ' : 'uopste', 
		'toll ' : 'sjajno, bajno', 
		'der Tanz ' : 'ples', 
		'tanzen ' : 'plesati', 
		'wollen ' : 'zeleti, hteti (situacija)', 
		'möchten ' : 'zeleti, hteti (stvari, predmet ... uctiviji oblik)', 
		'können ' : 'moci', 
		'los sein ' : 'desava se', 
		'los ' : 'ajde', 
		'jeder ' : 'svako', 
		'jede  ' : 'svaka', 
		'jedes ' : 'svaki', 
		'klar ' : 'jasno', 
		'nie ' : 'nikada', 
		'noch nie ' : 'nikada nisam ...', 
		'erklären ' : 'objasniti', 
		'anfangen ' : 'pocinjati (opsti oblik)', 
		'starten  ' : 'pocinjati (vazi sa masine, ...)', 
		'beginnen ' : 'pocinjati (vazi za odredjeni proces)', 
		'fangen ' : 'uhvatiti', 
		'üben (geübt)  ' : 'vezbati', 
		'über ' : 'iznad', 
		'das Team ' : 'tim', 
		'die Mannschaft ' : 'tim', 
		'singen ' : 'pevati', 
		'reiten ' : 'jahati', 
		'handstand machen ' : 'stajati na rukama', 
		'der Löffel ' : 'kasika', 
	},
	'04.02.2016' : {
		'eintragen ' : 'unosenje podataka', 
		'tragen ' : 'nositi', 
		'das Getränk / -e ' : 'pice', 
		'der Unterricht ' : 'predavanje', 
		'tun ' : 'ciniti, delovati, raditi (eng. do)', 
		'der Tipp / -s ' : 'savet', 
		'nur ' : 'samo', 
		'das Trinkgeld ' : 'napojnica', 
		'die Zeitschrift ' : 'casopis', 
		'die Sendung / -en ' : 'emisija', 
		'senden ' : 'emitoavti, poslati', 
		'das Beispiel ' : 'primer', 
	},
	'17.02.2016' : {
		'Beruf ' : 'zanimanje', 
		'scheinen ' : 'ciniti se, sijati', 
		'es scheint so ' : 'cini se tako', 
		'kann sein, kann nicht sein ' : 'moze bit, a ne mora', 
		'los ' : 'ajde', 
		'drenen ' : 'okrenuti', 
		'Tu nicht so! ' : 'ne budi takav!', 
		'seit ' : 'od (eng. since)', 
		'aufhören ' : 'zaustaviti se, prestati, stati (opsti oblik)', 
		'stoppen ' : 'zaustaviti se, prestati, stati (vozilo)', 
		'krank ' : 'bolestan', 
		'gesund ' : 'zdrav', 
		'der Unsinn ' : 'glupost (eng. nonsense)', 
		'verkaufen ' : 'prodavati', 
		'der Verkaufer ' : 'prodavac', 
		'die Blume / -n ' : 'cvet', 
		'die Unterschrift / -en ' : 'potpis', 
		'sich erinnern ' : 'prisetiti se', 
		'der Schauspieler ' : 'glumac', 
		'spielen ' : 'igrati, svirati, glumiti', 
		'wütend ' : 'besan', 
		'die Wut ' : 'bes', 
		'liefern ' : 'isporuciti, dostaviti', 
		'bringen ' : 'doneti', 
		'Exportkaufmann (m) ' : 'izvoznik', 
		'Exportkauffrau (f) ' : 'izvoznik', 
		'Seit wann? ' : 'od kada?', 
		'Wann haben Sie angefangen? ' : 'kada ste poceli?', 
		'Vor fünf Wochen ' : 'pre 5 nedelja', 
		'Wie lange? ' : 'Koliko dugo?', 
		'Bewerbung ' : 'propratno pismo (eng. application form)', 
		'Sehr geehrter ' : 'postovani', 
		'Wirtschaf ' : 'privreda', 
		'nächstes ' : 'sledeca', 
		'zur Verfügung stehen ' : 'stojim Vam na raspolaganju', 
	},
	'19.02.2016' : {
		'als ' : 'kao', 
		'der Beruf ' : 'zanimajne', 
		'die Ausbildung ' : 'obuka', 
		'die Geschichte ' : 'istorija, prica', 
		'Ledenschaft ' : 'strast (eng. passion)', 
		'wieder ' : 'ponovo', 
		'die Börse ' : 'berza', 
		'gerade ' : 'upravo, sada', 
		'gibt es ' : 'ima li, postoji li', 
		'geben ' : 'postojati, dati (e -> i)', 
		'enden ' : 'zavrsiti se, prestati', 
		'Mitte + <mesec> ' : 'sredinom meseca', 
		'früher ' : 'ranije', 
		'später ' : 'kasnije', 
		'fertig ' : 'gotovo', 
		'wenig ' : 'malo, nekoliko', 
		'im <mesec> ' : 'koristi se uz mesec', 
		'für ' : 'za, na ( uz vremenske odrednice )', 
		'der Gedanke / -n ' : 'misao', 
		'die Branche ' : 'ogranak, bransa', 
		'die Kenntniss ' : 'umece, znanje ( eng. knowhow )', 
		'die Dauer ' : 'trajanje', 
		'die Vereinbarung ' : 'dogovor', 
		'Schwerpunkt ' : 'fokus', 
		'erforderlich ' : 'potrebno', 
		'benötigt ' : 'potrebno', 
		'Führerschein ' : 'vozacka dozvola', 
		'die Bildung ' : 'obrazovanje', 
		'mindestens ' : 'najmanje, makar', 
		'bewerben ' : 'prijaviti se', 
		'betragen ' : 'iznositi (generalno)', 
		'Ungewöhnliche ' : 'neobicno', 
		'fremden ' : 'nepoznat', 
		'dürfen ' : 'smeti', 
		'darf ich? ' : 'smem li?', 
		'echt ' : 'pravo, prirodno', 
		'künstlich ' : 'vestacko', 
		'sicher ' : 'sigurno', 
		'setzen ' : 'sedati (gl)', 
		'sitzen ' : 'sedeti (stanje)', 
		'gemütlich ' : 'udobno', 
		'Gemütlichkeit ' : 'lagodnost, opustenost (vazi za juzni deo Nemacke)', 
		'die Lederhose ' : 'tregerice (m)', 
		'der Dirndl ' : 'zenska tradicionalna nosnja (f)', 
		'das Meer / -e ' : 'more', 
		'Schade ' : 'steta', 
	},
	'22.02.2016' : {
		'schaffen ' : 'zavrsiti, dovesti do kraja', 
		'der Traum ' : 'san', 
		'pflegen ' : 'negovati, starati se o necemu', 
		'draußen ' : 'napolju', 
		'beide ' : 'oboje, bilo koji (eng. both)', 
		'füttern ' : 'hraniti (decu, zivotinje, ...)', 
		'der Puppenspieler ' : 'lutkar', 
		'das Stück / -e ' : 'komad, prestava', 
		'der Kunde / -n ' : 'musterija', 
		'die Hochzeit / -en ' : 'vencanje', 
		'kennen lernen ' : 'upoznati', 
		'bekommen ' : 'dobiti', 
		'die Ratschläge ' : 'saveti', 
		'der Ratschlag ' : 'savet', 
		'unbedingt ' : 'nuzno, neophodno', 
		'der Dom ' : 'katedrala, hram', 
		'hingehen ' : 'otici tamo', 
		'Langsam, aber sicher ' : 'Polako, ali sigurno', 
		'der Ausflug ' : 'izlet', 
		'das Märchen ' : 'bajka', 
		'der Honig ' : 'med', 
		'die Kasse ' : 'kasa', 
		'das Ziel / -e ' : 'cilj, odrediste', 
		'auswählen ' : 'izabrati', 
		'der Preis / -e ' : 'nagraditi, cena', 
		'schieben ' : 'gurati', 
		'einschieben ' : 'ugurati', 
		'das Wechselgeld ' : 'kusur', 
		'stempeln ' : 'overiti, ponistiti', 
		'Man ' : '>> bezlicni oblik (eng. One)', 
		'    Man muss die Fahrkarte bezahlen ' : 'karta se mora kupiti', 
		'    Man bezahlt die Fahrkarte       ' : 'karta se placa', 
		'immer ' : 'uvek', 
		'Dann ' : 'potom, onda', 
		'dürfen ' : 'smeti', 
		'parken ' : 'parkirati', 
		'erlauben ' : 'dozvoljeno', 
		'verboten ' : 'zabranjeno', 
		'Das Schield ' : 'znak (saobracajni)', 
		'der Schield ' : 'viteski stit', 
		'mitnehmen ' : 'poneti sa sobom', 
		'ruhig gelegen ' : 'miran kraj', 
		'übernachtung ' : 'prenociste', 
		'übermorgen ' : 'prekosutra', 
		'bleiben ' : 'ostati', 
		'der Ausweis ' : 'licna karta', 
		'abgeben ' : 'predati', 
		'Das Gepäck ' : 'prtljag', 
	},
	'24.02.2016' : {
		'vergessen ' : 'zaboraviti', 
		'eintritt ' : 'ulazak', 
		'Turmbesteigungen ' : 'penjanje', 
		'berühmte ' : 'poznato', 
		'der Tempel ' : 'hram', 
		'Sehenswürdigkeit ' : 'znamenitost', 
		'der Tod ' : 'smrt', 
		'tot ' : 'mrtav', 
		'krank sein ' : 'biti bolestan', 
		'um was geht es? ' : 'o cemu se radi?', 
		'husten ' : 'kasljati', 
		'aussehen ' : 'izgledati', 
		'das Aussehen ' : 'izgled', 
		'das Auge / -n ' : 'oko / oci', 
		'zeigen ' : 'pokazati', 
		'entzündet ' : 'upaljeno ( pod upalom )', 
		'geschwollen ' : 'oteceno', 
		'weh tut ' : 'boleti', 
		'versuchen ' : 'pokusati, probati', 
		'in der Nähe ' : 'blizu, na dohvat ruke (eng. nearby, close by)', 
		'selbst ' : '(eng. self)', 
		'gefährlich ' : 'opasan', 
		'untersuchen ' : 'pregledati', 
		'vorsichtig ' : 'pazljivo', 
		'genau untersuchen ' : 'temeljno pregledati', 
		'das Haar ' : 'dlaka, kosa', 
		'der Kopf ' : 'glava', 
		'die Lippen ' : 'usne', 
		'der Mund ' : 'usta', 
		'der Hals ' : 'vrat, grlo', 
		'der Rücken ' : 'ledja', 
		'die Zehn ' : 'prsti na nogama', 
		'der Zeh ' : 'prst na nozi', 
		'der Fuß ' : 'stopalo', 
		'der Bauch ' : 'trbuh', 
		'die Zunge ' : 'jezik', 
		'gegen ' : 'protiv', 
		'der Schmerz ' : 'bol (dusevna)', 
		'die Schmerzen ' : 'bol (fizicka)', 
		'der Vernichtungsschmerz ' : 'izrazito jak bol', 
		'die Vernichten ' : 'unistiti', 
		'das Hemd ' : 'majica', 
		'sollen ' : 'trebati (trebalo bi)', 
		'rasu ' : 'napolje', 
		'vereinbaren ' : 'zakazati, ugovoit, dogovoriti', 
		'ändern ' : 'promeniti', 
		'absagen ' : 'otkazati', 
		'der Turm ' : 'toranj', 
		'täglich ' : 'svakodnevno, svaki dan', 
	},
	'26.02.2016' : {
		'bieten ' : 'nuditi', 
		'Freude ' : 'radost, sreca', 
		'Reiten ' : 'jahati', 
		'Treffpunkt ' : 'mesto sastajanja', 
		'Entspannung ' : 'opustanje, relaksacija', 
		'der Betreff ' : '(eng. subject)', 
		'die Anrede ' : 'pozdrav', 
		'der Empfänger ' : 'primaoc', 
		'Reiterhof ' : 'ergela, konjusarnica', 
		'anbieten ' : 'ponuditi', 
		'werden ' : 'postati (eng. become)', 
		'Entspannen ' : 'opustiti se', 
		'genießen ' : 'uzivati', 
		'vor Ort ' : 'na licu mesta', 
		'das Obst ' : 'voce', 
		'die Frucht /-˚˚e ' : 'vocka (jedna)', 
		'wahr ' : 'tacno, istinito', 
		'dick ' : 'debelo', 
		'einladen ' : 'pozvati', 
		'leider ' : 'nazalost', 
		'jemand ' : 'neko', 
	},
	'29.02.2016' : {
		'unterwegs ' : 'usput, biti na putu (kretati se)', 
		'fremde ' : 'nepoznato', 
		'hafen ' : 'luka', 
		'abholen ' : 'pokupit', 
		'das Heft / -e ' : 'sveska / e', 
		'backen ' : 'peci', 
		'der Bäcker ' : 'pekar', 
		'die Bretzel ' : 'pereca', 
		'die Bäckerei ' : 'pekara', 
		'aufpassen (hat aufgepasst) ' : 'obratiti paznju', 
		'achten ' : 'obratiti paznju ( pozornost )', 
		'eigentlich ' : 'zapravo', 
		'weinen ' : 'plakati', 
		'zuerst ' : 'prvo', 
		'allein ' : 'sam / sama / samo', 
		'verlieren ' : 'izgubiti', 
		'geradeaus ' : 'pravo (smer)', 
		'einfach ' : 'jednostavno', 
		'unten ' : 'dole', 
		'passieren ' : 'dogoditi se', 
		'gleich ' : 'odmah, isto (zavisi od konteksta)', 
		'der Bahnhof ' : 'zeleznicka stanica', 
		'die Post ' : '', 
		'die Metzgerei ' : 'mesara', 
		'zu Fuß ' : 'peske', 
		'mit +D ' : 'I (u srpskom)', 
		'das Messer ' : 'noz', 
		'das Flugzeug / -e ' : 'avion', 
		'der Verker ' : 'saobracaj, sex', 
		'der Flughafen / -˚˚ ' : 'aerodrom', 
		'der Straußenverker ' : 'ulicni saobracaj', 
		'die Bahn / -en ' : 'zeleznica, voz', 
		'an ' : 'do, naslonjen na', 
		'auf ' : 'na (stoji na necemu)', 
		'hinter ' : 'iza', 
		'in ' : 'u (necemu)', 
		'neben ' : 'pored', 
		'über ' : 'iznad', 
		'unter ' : 'ispod', 
		'vor ' : 'ispred', 
		'zwischen ' : 'izmedju', 
		'der Adler ' : 'orao', 
		'PKW - Personalkraftwagen ' : 'auto', 
		'LKW - Lastkraftwagen ' : 'kamion, teretno vozilo', 
		'die Last ' : 'teret', 
		'die Ampel ' : 'semafor', 
		'in dem ' : '> im (m, n)', 
		'in der ' : '> ø  (f)', 
		'in den ' : '> ø  (pl)', 
		'an dem ' : '> am', 
		'an der ' : '> ø', 
		'an den ' : '> ø', 
		'N ' : 'N', 
		'A ' : 'A + D', 
		'D ' : 'D + L + I', 
		'G ' : 'G', 
	},
	'02.03.2016' : {
		'die Wand ' : 'zid', 
		'zu ' : 'do', 
		'bei ' : 'kod', 
		'nach ' : 'posle, nakon', 
		'bei + dem ' : 'beim (m)', 
		'zu + dem ' : 'zum  (m)', 
		'zu + der ' : 'zur (f)', 
		'die Durchsage / -n ' : 'najava (zvucna)', 
		'die Abfahrt / ' : 'polazak', 
		'der Abflug / -˚˚e ' : 'polazak (avionom)', 
		'das Gleis ' : 'peron, sine', 
		'die Ankunft ' : 'dolazak', 
		'der Ausgang / -˚˚e ' : 'izlaz', 
		'der Eingang / -˚˚e ' : 'ulaz', 
		'einsteigen ' : 'ulazak', 
		'aussteigen ' : 'izlaziti', 
		'steigen ' : 'podizati, rasti, penjati se', 
		'umsteigen ' : 'presedanje', 
		'pünktlich ' : 'tacno na vreme', 
		'der Kunde ' : 'musterija', 
		'kaputt ' : 'nije u funkciji', 
		'reparieren ' : 'popravka', 
		'passen ' : 'odgovarati', 
		'aufsetzen ' : 'staviti', 
		'singen ' : 'pevati', 
		'wichtig ' : 'bitno', 
		'halten ' : 'drzati', 
		'behalten ' : 'zadrzati', 
		'zunächst ' : 'na pocetku, prvobitno', 
		'das Lied ' : 'pesma', 
		'bei (Zeit) ' : 'tokom, za vreme', 
		'vor (Zeit) ' : 'pre', 
		'bei (Zeit) ' : 'za', 
		'nach (Zeit) ' : 'posle', 
	},
	'04.02.2016' : {
		'Imbiss ' : 'kios brze hrane', 
		'hinauf ' : 'penjati se (obicno uz stepenice)', 
		'der Strich ' : 'crta (linija)', 
		'Stadtrundfahrt ' : 'obilazak grada (obucno autobusom - fahr)', 
		'Ab ' : 'od (vremenska odrednica)', 
		'Bis ' : 'do (vremenska odrednica)', 
		'von ' : 'od (vremenska odrednica)', 
		'Ab wann? ' : 'od kada?', 
		'die Aufgabe ' : 'zadatak, misija', 
		'schicken ' : 'poslati', 
		'höflich ' : 'uctivo, kulturno', 
		'buchen ' : 'rezervisati, bukirati', 
		'klingen ' : 'zvucati', 
		'der Fahrradständer ' : 'stalak za bicikle', 
		'die Kreuzung ' : 'raskrsnica', 
		'nicken ' : 'klimati glavom', 
		'der Verkehrsschild ' : 'saobracajni znak', 
		'die Leiche ' : 'les', 
		'leihen ' : 'iznajmiti (eng. borrow)', 
		'der Verleih ' : 'firma za iznajmljivanje necega', 
		'überall ' : 'svuda, svugde (prostorno)', 
		'anschließen ' : 'prikljuciti, staviti', 
		'schließen ' : 'zatvorit', 
	},
	'07.02.2016' : {
		'können ' : 'moci', 
		'werden ' : 'postati', 
		'das Kleid ' : 'haljina', 
		'die Kleider ' : 'odeca', 
		'schnell ' : 'brzo', 
		'schwer ' : 'tesko (tezina)', 
		'leicht ' : 'lako, jednostvno', 
		'schwierig ' : 'komplikovano', 
		'stehen ' : 'stajati, pristajati', 
		'gleich ' : 'isto', 
		'anders ' : 'drugacije', 
		'dauern ' : 'trajati', 
		'einfallen ' : 'imati ideju, dosetiti se necega', 
		'der Mantel ' : 'mantil', 
		'gehören ' : 'pripadati', 
		'ein notfall ' : 'hitan slucaj, nezgoda', 
		'günstig ' : 'povoljno', 
		'der Rock ' : 'suknja', 
		'gefallen ' : 'svidjati se (to please)', 
	},
	'09.02.2016' : {
		'gehören ' : 'pripadati', 
		'der | dieser   < ' : 'Welcher?', 
		'das | dieses   < ' : 'Welches?', 
		'die | diese    < ' : 'Welche?', 
		'die | diese    < ' : 'Welche?', 
		'Fundbüro ' : 'mesto za izgubljene stvari', 
		'der Schirm ' : 'kisobran', 
		'das Zeug ' : 'stvar (eng. stuff)', 
		'an ziehen ' : 'obuci, obuti', 
		'suchen ' : 'traziti', 
		'Untergeschoss ' : 'nivo/sprat (-1)', 
		'Erdgeschoss ' : 'nivo/sprat (0)', 
		'der Rock ' : 'suknja', 
		'feiern ' : 'proslaviti', 
		'aufpassen ' : 'obracati paznju', 
		'der See / -n ' : 'jezero', 
		'feiern = > die Feier ' : 'das Fest', 
		'die Feier ' : 'mala festa', 
		'das Fest ' : 'velika festa', 
		'herumfahren ' : 'voziti bez cilja', 
		'das Boot / -e ' : 'plovilo, camac', 
		'liegen ' : 'lezati', 
		'der Boden ' : 'pod', 
		'gratulieren ' : 'cestitati', 
		'vergessen ' : 'zaboraviti', 
		'der Rahmen ' : 'ram', 
		'die Ahnung ' : 'pozivitna sumnja', 
		'Keine Ahnung ' : 'nemam pojma', 
		'einladen ' : 'pozvati', 
		'überraschen ' : 'iznenaditi', 
		'das Geschenk ' : 'poklon', 
		'das Gift ' : 'otrov', 
		'der Wagen ' : 'kola', 
		'Mist ' : 'dodjavola (eng. Damn)', 
		'eilig haben ' : 'biti u zurbi', 
		'die Eile ' : 'zurba', 
		'denn ' : 'jer', 
		'ausgehen ' : 'izaci', 
		'der Bekannte ' : 'poznanik', 
		'die Kirche ' : 'crkva', 
		'die Prüfung ' : 'ispit', 
	},
	'11.02.2016' : {
		'das Ding ' : 'stvar (generalno)', 
		'zurzeit ' : 'sada', 
		'sich kümmern um +A ' : 'startai se, brinuti o... nekome, necemu', 
		'Schade ' : 'steta', 
		'ohne ' : 'bez', 
		'fast ' : 'uskoro (kolicina)', 
		'bald ' : 'uskoro (vreme)', 
		'laden ' : '(eng. load)', 
		'werden ' : 'postati', 
		'zumachen ' : 'zatvoriti', 
		'anmachen ' : 'ukljuciti, muvati (slang)', 
		'aufmachen ' : 'otvoriti', 
		'ausmachen ' : 'iskljuciti', 
		'der Arbeiter / - ' : 'radnik', 
		'die Stelle / -n ' : 'pozicija', 
		'das Jahr / -e ' : 'godina', 
		'die Woche / -n ' : 'nedelja', 
		'der Berg / -e ' : 'brdo, planina', 
		'das Land / ' : 'zemlja', 
		'die Idee / -n ' : 'ideja', 
		'die Stunde / -n ' : 'jedan sat', 
		'der Kindergarten / - ˚˚ ' : 'vrtic', 
		'das Abendessen / - ' : 'vecera', 
		'das Fenster / - ' : 'prozor', 
		'der Kalendar / - ' : 'kalendar', 
		'das Auto / -s ' : 'auto', 
		'das Foto / -s ' : 'fotografija', 
		'das Ticket / -s ' : 'karta', 
		'treffen (hat getroffen) ' : 'sresti', 
		'eilig ' : 'hitno', 
		'wunderbar ' : 'predivno', 
		'reisen (ist gereist) ' : 'putovati', 
		'helfen ' : 'pomoci', 
	},
	'23.03.2016' : {
		'hinfahren ' : 'voziti pravo', 
		'das Au-pair ' : 'bebisiterka', 
		'die Behörde / -n ' : 'drzavni cinovnik (administracija)', 
		'das Ding / -e ' : 'stvar', 
		'das Zeug ' : 'stvar', 
		'der Gegenstand ' : 'stvar', 
		'die Sache ' : 'stvar (abstraktno)', 
		'du Arme (f) ' : 'mukice, jadnice (u smislu sazaljenja)', 
		'du Armer (m) ' : 'mukice, jadniche (u smislu sazaljenja)', 
		'das Rad / -˚˚er ' : 'tocak', 
		'versuchen ' : 'probati, pokusati', 
		'der Sitz / -e ' : 'sediste', 
		'verlieren (+A) ' : 'izgubiti', 
		'nehmen +A ' : 'uzeti', 
		'schwierig ' : 'tesko (za rad)', 
		'schwer ' : 'tesko (tezina)', 
		'trennen ' : '> getrennt', 
		'trennen (hat getrennt) ' : 'odvojiti, razdvojiti', 
		'getrennt (pII) ' : 'odvojeno', 
		'einschlafen ' : 'zaspati', 
		'rechthaben ' : 'biti u pravu, imaiti pravo', 
		'schrecklich ' : 'strasno, jezivo', 
		'der Schreck ' : 'uplasiti, shok (eng. fear, shock)', 
		'verpassen (hat verpasst) ' : 'propustiti (prilika, prevozno sredstvo)', 
		'eigentlich ' : 'zapravo', 
		'denn ' : 'jer (veznik, nezavisna recenica)', 
		'weil ' : 'jer, zato sto, zbog (veznik, zavisna recenica)', 
		'einzige ' : 'jedino', 
		'einzig- ' : 'jedinstveni, jedan, jedini', 
		'bald ' : 'uskoro (vreme)', 
		'aufwachen ' : 'probuditi se', 
		'aufstehen ' : '> aufgestanden', 
		'aufwachen ' : '> aufgewachen', 
		'anrufen ' : '> angerufen', 
		'einkaufen ' : '> eingekauft', 
		'peinlich ' : 'blamaza', 
		'nämlich ' : 'naime, zapravo', 
		'steigen ' : 'rasti, penjati se, uci u neko vozilo', 
		'zurückfahren ' : 'vratiti se', 
		'ankommen ' : 'stici (negde, na cilj)', 
		'schließlich ' : 'konacno, na kraju, zakljucno', 
		'verpassen ' : '> verpasst', 
		'bekommen ' : '> bekommen', 
		'gehören ' : '> gehört', 
		'erleben ' : '> erlebt', 
		'passieren ' : '> passiert', 
		'erleben ' : 'doziveti', 
		'besichtigen ' : 'razgledati', 
		'der Zufall ' : 'slucajnost', 
		'sich melden ' : 'javi se', 
	},
	'28.03.2016' : {
		'Verwandtschaft ' : 'rodbina', 
		'der Schwager ' : 'zet', 
		'die Schwägerin ' : 'zetova sestra', 
		'der Erdgeschoss ' : 'prizemlje', 
		'die Dachwohnung / -en ' : 'potkrovlje', 
		'die allein erziehende Mutter ' : 'samohrana majka', 
		'der Müll ' : 'otpad', 
		'die Wand / -˚˚e ' : 'zid (unutra)', 
		'die Mauer ' : 'zid (spolja)', 
		'halten +A ' : 'drzati', 
		'die Müll ' : '> die Mülltonne', 
		'die Müll ' : 'otpad', 
		'die Mülltonne ' : 'kanta za otpad', 
		'der Hof ' : 'dvoriste', 
		'die Menge ' : 'kolicina', 
		'trennen ' : 'razdvojiti', 
		'getrennt ' : 'odvojeno', 
		'anders ' : 'drugacije', 
		'Recht haben ' : 'biti u pravu', 
		'klingen ' : 'zvucati', 
		'sorgen (hat gesorgt) ' : 'starati se', 
		'werfen ' : 'baciti (grudva, kamen ... u bukvalnom smislu)', 
		'wegwerfen ' : 'baciti (u smislu... otarasiti se)', 
		'wecken (hat gewecht) ' : 'probuditi se, uzbuditi se', 
		'das Amt ' : 'ministarstvo, sluzba', 
		'verbessern (hat verbessert) ' : 'popraviti', 
		'der Keller / - ' : 'podrum', 
		'zufrieden ' : 'zadovoljan', 
		'Die beiden ' : 'dvoje (eng. both)', 
		'der Haken ' : 'kuka', 
		'der Kasten ' : 'kutija', 
		'der Briefkasten ' : 'postansko sanduce', 
		'die Tafel ' : 'tabla', 
		'die Nichte ' : 'bratanica/sestricina', 
		'der Neffe ' : 'bratanac/sestric', 
		'verloren ' : 'izgubiti', 
		'schwanger ' : 'biti trudan', 
	},
	'30.03.2016' : {
		'rein ' : 'unutra (prefiks kretanja)', 
		'raus ' : 'napolje (prefiks kretanja)', 
		'rauf ' : 'gore (prefiks kretanja)', 
		'runter ' : 'dole (prefiks kretanja)', 
		'rüber ' : 'preko (prefiks kretanja)', 
		'runterbringen ' : 'saneti dole', 
		'raufbringen ' : 'doneti gore', 
		'rauskommen (ist rausgekommen) ' : 'izaci napolje', 
		'reinkommen (ist rausgekommen) ' : 'uci unutra', 
		'raufkommen (ist raufgekommen) ' : 'ici gore', 
		'das Amt / -˚˚er ' : 'ministarstvo, sluzba', 
		'der Anruf / -e ' : 'poziv (telefonski)', 
		'Tratsch ' : 'trach', 
		'das Mietshaus ' : 'zgrada', 
		'sonnig ' : 'suncano', 
		'der Streit ' : 'svadja', 
		'keine Ahnung ' : 'nemam pojma', 
		'Fürst ' : 'knez', 
		'einfallen +D ' : 'dosetiti se', 
		'der Kinderwagen ' : 'decja kolica', 
		'die Kiste / -n ' : 'kutija (obicno drvena)', 
		'abstellen (hat abgestellt) ' : 'ostaviti (nesto)', 
		'ausleihen (hat ausgeliehen) ' : 'pozajmiti', 
		'der Aufzug ' : 'lift', 
		'der Hausmeister / - ' : 'domar, kucepazitelj', 
		'unterwegs ' : 'usput, na putu', 
		'beruflich ' : 'poslovno (eng. bussiness)', 
		'hoffentlich ' : 'nadam se (eng. hopefully)', 
		'sei mir nich böse ' : 'nemoj se ljutiti na mene', 
		'schimpfen ' : 'grditi, psovati', 
		'die Mitteilung / -en ' : 'saopstenje', 
		'danach ' : 'posle', 
		'Wohngemeinschaft ' : 'cimeri, stambena zajednica', 
		'übrigens ' : 'usput (eng. btw)', 
		'gegen ' : 'oko (vremenski)', 
		'gießen (hat gegossen) ' : 'zalivati', 
		'die Pflanze / -n ' : 'biljka', 
		'der Strom ' : 'struja', 
		'verbraucht ' : 'potrositi', 
		'verbrauchen (hat verbraucht) ' : 'trositi', 
		'wahnsinnig ' : 'mnogo, bolesno mnogo', 
		'ärgerlich ' : 'frustrirajuce (eng. irritating)', 
		'furchtbar ' : 'strasno', 
		'furchtbar eilig ' : 'strasno zurim', 
		'es eilig haben ' : 'zurim', 
		'erwarten (hat erwartet) ' : 'ocekivati', 
		'Bescheid sagen ' : 'obavestiti', 
		'der Schmutz ' : 'prljavstina', 
		'sauber ' : 'cisto', 
		'schmutzig ' : 'prljavo', 
		'der Zettel / - ' : 'cedulja', 
		'der Boden / -˚˚e ' : 'pod', 
		'die Decke / -n ' : 'cebe, deka', 
		'das Regal / -e ' : 'regal', 
		'der Teppich / -e ' : 'tepih', 
		'die Toilete / -n ' : 'toalet', 
		'hängen (hat/ist gehangen, hat gehängt) ' : 'okaciti, obesiti', 
		'hoffen (hat gehofft) ' : 'nadati se', 
		'legen (hat/ist gelegen) ' : 'polegnuti', 
		'stellen (hat gestellt) ' : 'staviti', 
		'fröhlich ' : 'veseo', 
		'sauer ' : 'kiseo (raspolozenje)', 
		'traurig ' : 'tuzan', 
		'So ein Pech! ' : 'kakva steta', 
		'So ein Zufall! ' : 'kakva slucajnost', 
		'einziehen (ist eingezogen) ' : 'pokupiti, prisvojiti', 
		'erziehen (hat erzogen) ' : 'odgajati, trenirati (nekoga)', 
		'auf einmal ' : 'najednom', 
		'erst einmal ' : 'za pocetak, prvobitno', 
		'schon einmal ' : 'vec jednom', 
		'wenigstens ' : 'minimalno, bar malo', 
		'der Nachbar / -n ' : 'komsija', 
		'einrichten ' : 'organizovati, spremiti, uspostaviti', 
	},
	'04.04.2016' : {
		'nachsehen ' : 'proveriti', 
		'sorgen ' : 'brinuti se, pobrinuti se', 
		'sonst ' : 'inace', 
		'allgemein ' : 'inace, generalno', 
		'mundfaul ' : 'onaj koji slabo prica', 
		'der Durchschnitt ' : 'prosek', 
		'durchschnittlich ' : 'prosecno', 
		'die Gewohnheit ' : 'obicno, navika', 
		'die Nuss ' : 'orah, kostunjavo voce', 
		'fehlen ' : 'nedostajati (eng. to miss, to lack)', 
		'wach (sein) ' : 'budan (biti)', 
		'aufwachen ' : 'probuditi se', 
		'aufwecken +A ' : 'probuditi se', 
		'schläfrig ' : 'pospan', 
		'munter ' : 'oran, cio', 
		'weich ' : 'mekano', 
		'hart ' : 'tvrdo', 
		'ausschlafen ' : 'naspavati se', 
		'die Störung ' : 'smetnja', 
		'(sich) entscheiden ' : 'odluciti (se)', 
		'frisch ' : 'sveze', 
		'dazu ' : 'dodatno (nedovoljno)', 
		'stark ' : 'jako', 
		'schwach ' : 'slabo', 
		'aussagen ' : 'tvrditi, otkriti', 
		'die Tasse / -n ' : 'solja', 
		'der Kakau ' : 'kakao', 
		'der Fan ' : 'fan', 
		'der Bettelmann ' : 'prosjak, siromah', 
		'handeln ' : '> die Handlung', 
		'die Handlung ' : 'tema', 
		'verschieden ' : 'razlicito', 
		'anders ' : 'drugacije', 
		'ähnlich ' : 'slicno', 
		'gleich ' : 'isto, odmah', 
		'identisch ' : 'identicno', 
		'Ehrlich ' : 'iskreno', 
		'allerdings ' : 'niposto, nikako, zapravo', 
		'Gott sei Dank ' : 'bogu hvala', 
		'die Menge ' : 'kolicina', 
		'besonders ' : 'posebno', 
		'tagelang ' : 'danima', 
		'stundenlang ' : 'satima', 
		'jahrelang ' : 'godinama', 
		'wochenlang ' : 'nedeljama', 
		'reden (hat geredet) ' : 'pricati', 
		'der Gott ' : 'bog', 
		'nachgefragt < ' : 'nachfragen', 
		'nachfragen ' : 'propitati', 
		'drinnen ' : 'unutra', 
		'draußen ' : 'napolju', 
		'sogar ' : 'cak', 
		'der Sekt ' : 'penusavo vino', 
		'herzhaft ' : 'prijatno (srcu)', 
		'fast ' : 'skoro (eg. 99%)', 
		'bald ' : 'uskoro (eg. 19h55)', 
		'immer ' : 'uvek', 
		'meistens ' : 'uglavnom', 
		'oft ' : 'cesto', 
		'manchmal ' : 'ponekat', 
		'selten ' : 'retko', 
		'nie ' : 'nikada', 
		'mittags ' : 'u podne', 
		'morgens ' : 'ujutro', 
		'abends ' : 'uvece', 
		'werktags ' : 'radni dani', 
		'wochentags ' : 'dani u nedelji', 
	},
	'06.04.2016' : {
		'das Vollkornbrot ' : 'hleb sa semenkama', 
		'Rinderbraten ' : 'telece pecenje', 
		'braten (hat gebraten) ' : 'peci ', 
		'der Kürbis ' : 'bundeva', 
		'der Essig ' : 'sirce', 
		'außerdem ' : 'osim toga', 
		'die Bude ' : 'mali prostor, gajba', 
		'Mahlzeit ' : 'obrok, guten appetit', 
		'holen ' : 'otici uzeti nesto i doneti (ceo postpupak)', 
		'dagegen ' : 'naprotiv, sa druge strane', 
		'nirgends ' : 'nigde', 
		'genauso ' : 'podjednako, kao, slicno kao', 
		'unterschiedliche ' : 'drugacije', 
		'die Art ' : 'vrsta', 
		'beschäftigen ' : 'baviti se, uzimati paznju', 
		'widmen ' : 'postetiti', 
		'die Widmung ' : 'posveta', 
		'schneiden (hat geschnitten) ' : 'seci', 
		'darüber ' : 'preko toga', 
		'das Gericht ' : 'obrok', 
		'geheimen ' : 'tajno, sakrivajuci se', 
		'geheim ' : 'tajna', 
		'das Rezept ' : 'recept', 
		'herstellen ' : 'proizvoditi', 
		'himmlisch ' : 'nebesko, rajsko', 
		'ehemaligen ' : 'bivsi', 
		'der Regierungschef ' : 'premier', 
		'die Einladung ' : 'pozivnica', 
		'das Benehmen ' : 'bonton', 
		'die Regel ' : 'pravilo', 
		'dauren ' : 'trajati', 
		'die Dauer ' : 'traje', 
		'ausmachen ' : 'dogovoriti se, iskljuciti', 
		'die Verspätung ' : 'kasnjenje', 
		'die Nachspeise ' : 'dezert', 
		'die Weile ' : 'neodredjeno vreme (dugo ili kratko)', 
		'der Gastgebern ' : 'domacin', 
		'satt ' : 'sit', 
		'übrig ' : 'visak', 
		'nötig ' : 'neophodno, potrebno', 
		'das Gebäck ' : 'pecivo', 
		'der Teig ' : 'testo', 
		'die Sorte ' : 'sorta', 
		'schicken ' : 'poslati (fizicki)', 
		'senden ' : 'poslati (elektronski)', 
		'die Stange / -n ' : 'stangla', 
		'prima ' : 'super', 
		'die Backstube ' : 'soba sa pecnicom', 
		'sparen (hat gespart) ' : 'stedeti, sparati', 
		'probieren ' : 'pokusati, okusiti', 
		'fett ' : 'mast', 
		'frisch ' : 'sveze', 
		'salzig ' : 'slano', 
		'sauer ' : 'kiselo', 
		'scharf ' : 'ljuto, ostro', 
		'süß ' : 'slatko', 
		'die Bohne / -n ' : 'pasulj', 
		'der Braten / - ' : 'peceno', 
		'die Gabel / -n ' : 'viljuska', 
		'der Becher / - ' : 'solja', 
		'die Pfanne / -n ' : 'tiganj', 
		'die Schüssel / -n ' : 'cinija', 
		'die Tasse / -n ' : 'solja', 
		'der Topf / -˚˚e ' : 'serpa', 
		'duschen (hat geduscht) ' : 'tusirati se', 
		'lassen (hat gelasse) ' : 'pustiti, dozvoliti', 
		'besetzt ' : 'zauseti', 
	},
	'11.04.2016' : {
		'Welch ' : 'stranac (staro nemacki)', 
		'Ostsee ' : 'Balticko more', 
		'Ratschlag ' : 'savet, predlog', 
		'beachten ' : 'obratiti paznju na nesto', 
		'achten ' : 'pazi na ...', 
		'sachliche ' : 'strucno', 
		'beendet ' : 'zavrsiti, okoncati', 
		'beantworten ' : 'odgovoriti', 
		'der Rat ' : 'savet', 
		'überstunden ' : 'prekovremeno vreme', 
		'übertreiben ' : 'preterivati', 
		'Wenn ' : 'ako', 
		'Dann ' : 'jer', 
		'die Teilzeit ' : 'pola vremena (radnog)', 
		'betrunken ' : 'pijan', 
		'da vorn ' : 'tamo napred', 
		'der Arbeitsplatz ' : 'radno mesto', 
		'ausrichten +A ' : 'informisati <A>', 
		'außer ' : 'van(i)', 
		'die Durhwahl ' : 'pozivni broj', 
		'noch nicht ' : 'jos ne', 
		'insgesamt ' : 'sve ukupno', 
		'die Spitze ' : 'vrh', 
		'zumindest ' : 'minimalno', 
		'betreffen ' : 'ticati se', 
		'Angestellten ' : 'zaposleni', 
		'das Büro / -s ' : 'kancelarija', 
		'der Empfang / -˚˚e ' : 'prijem', 
		'der Eport / -e ' : 'izvoz', 
		'die Fabrik / -en ' : 'fabrika', 
		'die Maschine / -n ' : 'masina', 
		'die Mehrwertsteuer ' : 'PDV', 
		'das Produkt / -e ' : 'proizvod', 
		'die Quittung / -en ' : 'racun (eng. receipt)', 
		'die Überstunde / -n ' : 'prekovremeno (eng. overtime)', 
		'außer Haus ' : 'van kuce', 
		'das Gebäck ' : 'kolacici', 
		'der Hammer / -˚˚ ' : 'cekic', 
		'das Handwerk ' : 'rucni rad', 
		'der Handwerker ' : 'zanatlija (eng. craftsman)', 
		'die Nagel ' : 'ekser', 
		'der Meister ' : 'sampion, majstor, ekspert', 
		'das Holz / -˚˚er ' : 'drvo (materijal)', 
		'der Vogel / -˚˚ ' : 'ptica', 
		'der Wald / -˚˚er ' : 'suma', 
		'die Meinung / -en ' : 'misljenje', 
		'der Rat ' : 'savet, pacov', 
		'das Symbol / -e ' : 'simbol', 
		'der Teil / -e ' : 'deo, sekcija, poglavlje', 
		'der Typ / -en ' : 'tip', 
		'anbieten (hat angeboten) ' : 'ponuditi, obezbediti', 
		'abschließen (hat abgeschlossen) ' : 'zakljucati, zavrsiti', 
		'ausgeben (hat ausgegeben) ' : 'potrositi, rasprsiti, pustiti', 
		'ausschalten (hat ausgeschalten) ' : 'onesposobiti, ugasiti, iskljuciti', 
		'entscheiden (hat entschieden) ' : 'odluciti', 
		'erkennen (hat erkannt) ' : 'prepoznati, detektovati', 
		'merken (hat gemerkt) ' : 'zapaziti, zapisati, skrenuti paznju na netso (zameriti)', 
		'spülen (hat gespült) ' : 'prati, pustiti vodu', 
		'stören (hat gestört) ' : 'uznemiravati, remetiti, mesati se', 
		'wählen (hat gewählt) ' : 'birati (telefonski broj)', 
		'übersetzen (hat übersetzt) ' : 'prevoditi', 
		'gleichfalls ' : 'takodje', 
	},
	'18.04.2016' : {
		'der Korkenzieher ' : 'otvarac za vino', 
		'das All ' : 'univerzum', 
		'der Weltraum ' : 'univerzum', 
		'der Notfall ' : 'hitan slucaj (eng. emergency)', 
		'überleben ' : 'preziveti', 
		'das Gepäck ' : 'prtljag', 
		'Bergsteiger ' : 'alpinista', 
		'weltweit ' : 'sirom sveta (eng. worldwide)', 
		'häufig ' : 'cesto', 
		'Gebrauchen ' : 'koristiti', 
		'kaputtgehen ' : 'pokvariti se', 
		'Haushalt ' : 'domacinstvo, budzet', 
		'irgendwo ' : 'igde, bilo gde', 
		'kunststoff ' : 'vestacki materijal', 
		'der Stoff ' : 'materijal', 
		'überall ' : 'svugde', 
		'der Schmied ' : 'kovac', 
		'der Messerschmied ' : 'proizvodjac nozeva', 
		'gründen ' : 'osnovati (firmu)', 
		'der Grund ' : 'osnova', 
		'eigen ' : 'privatni, posedovati', 
		'die Kündigung ' : 'otkaz, otpust', 
		'das Unternehmen ' : 'preduzece', 
		'Familienunternehmen ' : 'porodicno preduzece', 
		'der Urenkel ' : 'praunuk', 
		'mitarbeiter ' : 'saradnik', 
		'faul ' : 'lenj, truo', 
		'lam ' : 'trom', 
		'die Kinderheit ' : 'detinjstvo', 
		'denken (hat gedacht) ' : 'misliti', 
		'geben ' : 'dati, postojati', 
		'der Lärm ' : 'buka', 
		'"wie es geht" ' : 'kako se to radi', 
		'"wie es geht" ' : '> wie man dass macht', 
		'(sich) umziehen ' : 'presvuci (se)', 
		'meckern ' : 'zvocati, kukati', 
		'bügeln ' : 'peglati', 
		'das Bügeleisen ' : 'pegla', 
		'kichern ' : 'kikotati se', 
		'das Gekicher ' : 'kikot', 
		'sich bewegen ' : 'kretati se', 
		'dick ' : 'debeo', 
		'fett ' : 'debeo (abnormalno), mast', 
		'dünn ' : 'mrsav', 
		'dürr ' : 'zgoljav, ispijen', 
		'der Körüer ' : 'telo', 
		'mitmachen ' : 'ucestvovanje', 
	},
	'20.04.2016' : {
		'so viel ' : 'tako mnogo', 
		'zu viel ' : 'previse', 
		'zu wenig ' : 'premalo', 
		'der Baum ' : 'drvo (biljka)', 
		'möglichst ' : 'sto je moguce ... vise/manje', 
		'sich bewegen ' : 'kretati se', 
		'sich rasieren ' : 'brijati se', 
		'bewegen ' : 'pomeriti +A', 
		'die Bewegung ' : 'pokret (generalno)', 
		'gleich ' : 'isto, odmah', 
		'runterfallen ' : 'pasti dole', 
		'fühlen ' : 'osecati', 
		'schwach ' : 'slab', 
		'danach ' : 'potom, zatim', 
		'ausruhen ' : 'odmoriti se', 
		'hochlegen ' : 'podici', 
		'sich ernähren ' : 'hraniti se', 
		'die Nahrung ' : 'namirnica', 
		'die Ernährung ' : 'dijeta, nutricionizam', 
		'sich ärgern ' : 'nervirati se', 
		'der Ärger ' : 'problem, nevolja', 
		'sich erkälten ' : 'biti prehladjen', 
		'stärken ' : 'jacati', 
		'schwächen ' : 'slabiti', 
		'zufrieden sein ' : 'biti zadovoljan', 
		'der Ergebnis ' : 'rezultat', 
		'sich treffen +D ' : 'sresti se', 
		'treffen ' : 'sudariti se', 
		'sich verabreden ' : 'dogovoriti se', 
		'Kleinigkeit ' : 'sitnica', 
		'kaum ' : 'jedva', 
		'sich kümmern um ' : 'cuvati, paziti nekoga', 
		'sich beschweren über ' : 'zaliti se', 
		'denken an ' : '> Woran denkst du?', 
		'warten auf ' : '> Worauf wartest du?', 
		'sich erinnern ' : 'setiti se', 
	},
	'25.04.2016' : {
		'der Sonnenschein ' : 'sija sunce', 
		'die Wäsche ' : 'ves', 
		'trocknen ' : 'susiti', 
		'der Kampfsport ' : 'borilacki sport', 
		'anstrengend ' : 'naporno / naporan / naporna', 
		'reichen ' : 'biti dovoljno', 
		'Begriff ' : 'pojam, koncept', 
		'radeln ' : 'voziti biciklo', 
		'die Liegestütze ' : 'sklekovi', 
		'die Kniebeugen ' : 'cucnjevi', 
		'außer Betrieb ' : 'van funkcije', 
		'entfernt ' : 'udaljeno', 
		'entfernen ' : 'udaljiti', 
		'Mitglied ' : 'clan', 
		'der Alltag ' : 'svakodnevno', 
	},
	'27.04.2016' : {
		'werden ' : '> geworden', 
		'werden ' : 'postati', 
		'sogar ' : 'cak', 
		'bestimmt ' : 'sigurno', 
		'Bundesland ' : 'pokrajina', 
		'das Gebirge ' : 'skup planina', 
		'wunderschöne ' : 'prelepo', 
		'Landschaft ' : 'pejzaz', 
		'Hilfsmittel ' : 'pomagalo', 
		'das Seil ' : 'uze, konopac', 
		'der Gipfeln ' : 'vrh, samit', 
		'der Weg ' : 'put (uopsteno)', 
		'das Gebit ' : 'oblast', 
		'meistbesuchten ' : 'najposeceniji', 
		'nachsehen ' : 'proverit', 
		'der Fels ' : 'stena (u zemlji)', 
		'der Felsen ' : 'planinska stena', 
		'berühmt ' : 'slavan', 
		'erfolg ' : 'uspeh', 
		'erfolgreich ' : 'uspesan', 
		'sterben ' : 'umreti', 
		'im Alter von 77 Jahren ' : 'u 77 godini starosti', 
		'die Karriere ' : 'karijera', 
		'das Zeugnis ' : 'svedocanstvo', 
		'das Fach ' : 'predmet', 
		'der Fachmann ' : 'strucnjak', 
		'die Note ' : 'nota, ocena', 
		'das Abitur ' : 'matura', 
		'die Abschlussprüfung ' : 'maturski ispit', 
		'hassen (hat gehasst) ' : 'mrzeti', 
		'lieben ' : 'voleti', 
		'reich ' : 'bogat', 
		'arm ' : 'siromasan', 
		'fleißig ' : 'marljiv', 
		'verdinen ' : 'zaraditi, zasluziti', 
		'anscheinend ' : 'naizgled', 
		'los sein ' : 'sta se desava', 
		'los lassen ' : 'pustiti', 
		'die Erziehung ' : 'vaspitanje', 
		'der Erziehungsberechtigte ' : 'staratelj', 
		'der Hass ' : 'mrznja', 
		'dankbar (sein) ' : '(biti) zahvalan', 
		'froh sein ' : 'biti radostan', 
		'die Ruhe ' : 'mir', 
		'streng ' : 'strog', 
		'gerecht ' : 'pravican', 
		'die Biene ' : 'pcela', 
		'umgekehrt ' : 'obrnuto', 
		'der Aufsatz ' : 'sastav', 
	},
	'04.05.2016' : {
		'vermissen ' : 'nedostajati', 
		'erholen ' : 'odmoriti', 
		'schaffen ' : 'uspeti, stvarati', 
		'kostbar ' : 'dragoceno', 
		'erwähnen ' : 'spomenuti', 
		'wollen ' : '> wollte', 
		'können ' : '> konnte', 
		'sollen ' : '> sollte', 
		'dürfen ' : '> durfte', 
		'mussen ' : '> musste', 
		'die Lücke / -n ' : 'praznina', 
		'die Parklücke ' : 'prazno mesto (na parkingu)', 
		'andersherum ' : 'obrnuto (eng. vice versa)', 
		'lesbar ' : 'citljivo', 
		'der Bauernhof ' : 'seosko imanje', 
		'der Bauer ' : 'paor, ratar', 
		'die Bäuerin ' : 'paorka, ratarka', 
		'die Lehre ' : 'zanat', 
		'erkennbar ' : 'prepoznatljivo', 
		'die Zutat / -en ' : 'sastojak', 
		'der Pilz / -e ' : 'pecurka', 
		'man hat, man kann ' : 'ima se, moze se', 
		'dass ' : 'da, sto', 
		'der Erfolg ' : 'uspeh', 
	},
	'09.05.2016' : {
		'das Dach ' : 'krov', 
		'der Verein ' : 'udruzenje, klub', 
		'der Sportverein ' : 'sportski klub', 
		'das Gespür ' : 'njuh, osecaj', 
		'der Azubi ' : 'potrcko, "omladinac"', 
		'die Erdkunde ' : 'geografija', 
		'das Felt ' : 'oblast, region', 
		'mitmachen ' : 'ucestvovati', 
		'die Teilnehmer ' : 'ucesnik', 
		'die Fee ' : 'vila', 
		'vorstellen ' : 'zamisljati', 
		'erfüllen ' : 'ispuniti, zavrsiti', 
		'überlegen (hat überlegt) ' : 'razmotriti, premisljati se', 
		'tatsächlich ' : 'cinjenicno, stvarno', 
		'innerhalb ' : 'unutar', 
		'die Ehe ' : 'brak', 
		'der/die Angestellte / -n ' : 'sluzbenik', 
		'der Anwalt / -˚˚e ' : 'advokat', 
		'die Anwältin / -nen ' : 'advokatica', 
		'der Arbeitgeber / - ' : 'poslodavac', 
		'der Arbeitnehmer / - ' : 'radnik', 
		'der Arbeitsplatz / -˚˚e ' : 'radno mesto', 
		'der/die Auszubildende / -n ' : 'pripravnik, onaj koji se obucava', 
		'die Bewerbung / -en ' : 'prijava, kandidatura', 
		'die Kündigung / -en ' : 'ostakvka, prekid rada, povlacenje, otpustanje', 
		'die Lehre / -n ' : 'nauk, pouka, savet, iskustvo, segrtovanje', 
		'    in der Lehre sein ' : 'uciti zanat', 
		'    in die Lehre geben ' : 'dati na zanat', 
		'der Lohn / -˚˚e ' : 'plata, isplata, nagrada, zarada', 
		'die Krippe / -n ' : 'jasle', 
		'der Kindergarten / -˚˚ ' : 'vrtic', 
		'die Grundschule / -n ' : 'osnovna skola', 
		'die Gesamtschule / -n ' : 'opsta skola (srednja)', 
		'das Gymnasium ' : 'gimnazija', 
		'die Hauptschule / -n ' : 'niza srednja skola', 
		'die Realschule / -n ' : 'srednja skola', 
		'die Berufsschule / -n ' : 'zanat', 
		'das Abitur ' : 'matura', 
		'das Fach / -˚˚er ' : 'predmet', 
		'der Körper / - ' : 'telo', 
		'der Notarzt / -˚˚e ' : 'doktor hitne pomoci', 
		'bluten ' : 'krvariti', 
		'verletzt ' : 'povredjen', 
		'der Ärger ' : 'nevolja, iritirajuce', 
		'die Angst / -˚˚e ' : 'strah, anksioznost', 
		'die Beratung / -en ' : 'konferencija, konsultacija', 
		'die Einführung / en ' : 'prihvatanje necega, implementacija, inicijacija', 
		'die Erfahrung / -en ' : 'iskustvno, empirijsko znanje', 
		'das Frühjahr ' : 'prolecno doba', 
		'das Gegenteil ' : 'suprotnost', 
		'die Gesellschaft / -en ' : 'drustvno, korporacija, organizacija', 
		'die Sorge / -n ' : 'briga, tuga, strah', 
		'der Wunsch / -˚˚e ' : 'zelja', 
		'die Voraussetzung / -en ' : 'predpostavka, uslov (eng. preequisite)', 
		'drucken (hat gedruckt) ' : 'stampati', 
		'erreichen (hat erreicht) ' : 'postici, dokuciti, pridobiti', 
		'Interesse haben (an) ' : 'biti zainteresovan (za)', 
		'speichern (hat gespeichert) ' : 'sacuvati, snimiti memorisati', 
		'teilnehmen (hat teilgenommen) ' : 'ucestvovati', 
		'verändern (hat verändert) ' : 'izmeniti, promenti', 
		'verdienen (hat verdient) ' : 'zaraditi, zasluziti', 
		'vergessen (hat vergessen) ' : 'zaboraviti', 
		'schriftlich ' : 'napismeno', 
		'verschieden ' : 'razlicito', 
		'die Kunst ' : 'umetnost', 
	},
	'16.05.2016' : {
		'flüstern ' : 'saputati', 
		'das Altersheim ' : 'staracki dom', 
		'die Stimme ' : 'glas', 
		'stimmen ' : 'biti u pravu, stimovati', 
		'der Witzbold ' : 'saljivdzija', 
		'vergehen (Zeit) ' : 'prolaziti (vreme)', 
		'die Verwandten ' : 'rodjaci', 
		'mitkommen ' : 'poci sa nekim', 
		'klingen + wie ' : 'zvucati', 
		'allein ' : 'sam(a/o)', 
		'selbstgebacken ' : 'samostalno ispekao', 
		'ausmachen ' : 'iskljuciti', 
		'taub ' : 'gluv', 
		'blind ' : 'slep', 
		'stumm ' : 'nem', 
		'zerscheiden ' : 'iseci', 
		'schenken ' : 'pokloniti', 
		'sich vorstellen ' : 'zamisliti, predstaviti se', 
		'das Gewissen ' : 'savest', 
		'der Strauß ' : 'buket, noj (ptica)', 
		'die Blumenstrauß ' : 'buket cveca', 
		'drücken ' : 'pritiskati', 
		'angehen ' : 'ukljuciti se', 
	},
	'23.05.2016' : {
		'die Luft ' : 'vazduh', 
		'die Voraussetzung ' : 'preduslov', 
	},
	'06.06.2016' : {
		'vor mir aus ' : 'sto se mene tice, naravno, nema problema', 
		'wichtig ' : 'bitno', 
		'unwichtig ' : 'nebitno', 
		'besonders ' : 'posebno', 
		'gerecht ' : 'pravedno', 
		'ungerecht ' : 'nepravedno', 
		'Ohne Fleiß keine Preis ' : 'bez muke nema nauke', 
		'die Ruhe ' : 'mir', 
		'unternehmen ' : 'preduzeti', 
		'ausrechnen ' : 'izracunati', 
		'spielen ' : 'igrati se, svirati, kockati se', 
		'das Stück ' : 'komad', 
		'rausbekommen ' : 'saznati (ispitivanjem obicno)', 
		'schlank ' : 'vitak', 
		'dick ' : 'debeo', 
		'klingen ' : 'zvoniti', 
		'leuten ' : 'zvoniti na crkvi', 
		'stören ' : 'uznemiravati', 
		'ärgern ' : 'iritirati', 
		'keine Ausreden ' : 'nema izgovora', 
		'Deutschlerner jammern nicht! ' : 'ucenik Nemackog ne kuta!', 
		'trotzdem ' : 'uprkos', 
		'auf keine Fall ' : 'niukom slucaju', 
		'die Veranstaltung ' : 'dogadjaj (kulturni)', 
		'veranstalten ' : 'organizovati', 
		'genießen +A ' : 'uzivati', 
		'verbringen ' : 'provesti (vreme)', 
	},
	'08.06.2016' : {
		'umfrage ' : 'upitnik', 
		'leserumfrage ' : 'anketa citalaca', 
		'haben          ' : '> Ich hätte gern ...', 
		'sein           ' : '> Ich wäre gern ...', 
		'werden + Inf   ' : '> Ich würde gern ...', 
		'die Blase ' : 'mehur, besika', 
		'ausgezeichnet ' : 'odlikovan, odlicno', 
		'die Gänsehaut ' : 'jeziti se, pacja koza', 
		'der Flohmarkt ' : 'buvljak', 
		'das Kaufhaus ' : 'robna kuca', 
		'die Auswahl ' : 'izbor', 
		'die Ware ' : 'roba', 
		'neu ' : 'novo', 
		'gebraucht ' : 'koristeno', 
		'mal sehen ' : 'pogledacemo', 
		'handeln ' : 'trgovati, cenjkati se', 
		'feilschen ' : 'cenjkati', 
	},
	'13.06.2016' : {
		'städtisch ' : 'gradski', 
		'Haushaltwaren ' : 'roba za kucu', 
		'die Sohle ' : 'djon', 
		'der Bildschirm ' : 'ekran', 
		'die Fußsohle ' : 'taban', 
		'die Schiff ' : 'brod', 
		'die Fahrt ' : 'voznja', 
		'die Schifffahrt ' : 'voznja brodom', 
		'tief ' : 'duboko', 
		'verzeihung ' : 'izvinite, oprostite', 
		'Turnschuhe ' : 'baletanke', 
		'Eisenbahn ' : 'zeleznica', 
		'Woraus? ' : 'od cega?', 
		'die Flagge ' : 'zastava', 
		'der Kreis ' : 'krug', 
		'der Jahrmarkt ' : 'vasar', 
		'damit ' : 's`njim, time', 
		'die Gurke ' : 'krastavac', 
		'-tuch (postfix) ' : 'bilo kakvo parce tkanine', 
		'Tischtuch ' : 'stonjak', 
		'zugreifen ' : 'ugrabiti', 
		'Deckelöffner ' : 'otvarac', 
		'wie (=) ' : '> za komparaciju kada je isto', 
		'als (<>) ' : '> za komparaciju kada je razlicito', 
		'der Sessel ' : 'fotelja', 
		'das Besteck ' : 'escajg', 
		'das Geschirr ' : 'sudovi', 
	},
	'15.06.2016' : {
		'eng ~ schmal ' : 'usko', 
		'auf den Wecker gehen ' : 'ici na nerve nekome', 
		'flach ' : 'plitko', 
		'tief ' : 'duboko', 
		'eckig ' : 'coskasto, kockasto', 
		'rund ' : 'okruglo', 
		'ziemlich ' : 'poprilicno, izrazito', 
		'kuckuck ' : 'kukavica (ptica)', 
		'der Kleber ' : 'lepak', 
		'kleben ' : 'lepiti', 
		'der Zeiger ' : 'kazaljka', 
		'locker ' : 'labavo, klimavo', 
		'schaffen ' : 'zavrsiti nesto uspesno', 
		'reinschreiben ' : 'upisati', 
		'spinnen ' : 'biti lud', 
		'der Spinner ' : 'ludak, diabola (osobina)', 
		'die Schere ' : 'makaze', 
		'witzig ' : 'zabavno, smesno, vickasto', 
		'verpacken ' : 'pakovati', 
		'wiegen ' : 'izmeriti tezinu', 
		'das Gewicht ' : 'tezina', 
		'sich beeilen ' : 'pozuriti', 
		'leeren ' : 'prazniti', 
		'erreichen ' : 'dohvatiti, dosegnuti', 
		'nebenan ' : 'odmah do, vrata do', 
		'deshalb ' : 'stoga', 
		'das Wissen ' : 'znanje', 
		'sich besorgen ' : 'nabaviti', 
	},
	'20.06.2016' : {
		'der Anrufbeantworter ' : 'sekretarica', 
		'ich habe frei Zeit ' : 'imam vremena', 
		'der Hagel ' : 'grad (vremenski uslov)', 
		'hageln ' : 'pada grad', 
		'die Hitze ' : 'vrucina', 
		'    die Hitze bekommt mir nicht ' : 'vrucina mi ne prija', 
		'feuch ' : 'vlazno', 
		'die Feuchtigkeit ' : 'vlaznost', 
		'nass ' : 'mokro', 
		'die Nässe ' : 'mokrost (vlaznost)', 
		'Was für? ' : 'Kakav?', 
		'der Galgenhumor ' : 'posebna vrsta crnog humora', 
		'vertragen ' : 'podnositi (fizicki)', 
		'    ich vertrage die Hitze nicht ' : 'ne podnosim vrucinu', 
		'bauen ' : 'konstruisati', 
		'selbstbauen ' : 'samostalno konstruisati', 
		'die Wanderschuhe ' : 'obuca za planinarenje', 
		'beanragen ' : 'podnositi, aplicirati', 
		'verlängern ' : 'produziti', 
		'sich bewerben ' : 'konkurisati', 
		'retten ' : 'spasiti', 
		'das Vorstellungsgespräch ' : 'prvi razgovor, intervju', 
		'der Stress ' : 'stres', 
		'die Fortbildung ' : 'dalje usavrsavanje', 
		'vermissen +A ' : 'propustiti', 
		'der Sportplatz ' : 'igraliste', 
		'die Ecke ' : 'ugao, cosak, ivica', 
		'die Reinigung ' : 'ciscenje', 
		'    ich stelle mir einen Wagen vor ' : 'zamisljam sebi jedan auto', 
		'die Ausrede ' : 'izgovor', 
		'die Kneipe ' : 'pub, bar', 
		'eher ' : 'radije', 
		'teilweise ' : 'delimicno', 
		'ständig ' : 'konstantno', 
		'Plötzlich ' : 'iznenada', 
		'sich unterhalte ' : 'razgovarati', 
	},
	'22.06.2016' : {
		'das Vorurteil ' : 'predrasuda', 
		'missverständnis ' : 'nesporazum', 
		'verständnis ' : 'razumevanje', 
		'anreden ' : 'osloviti, obratiti se', 
		'herausfunden ' : 'saznati, doznati', 
		'doppelt ' : 'duplo (kolicinski)', 
		'auffordern ' : 'zatraziti, apelovati', 
		'unterbrichen ' : 'prekinuti', 
		'während ' : 'dok (eng. while)', 
		'der Streit ' : 'svadja', 
		'der Zank ' : 'svadja', 
		'die Faust ' : 'pesnica', 
		'einverstanden ' : 'biti saglasan', 
		'aussagen ' : 'izjaviti', 
		'quälen ' : 'muciti', 
		'unangenehm ' : 'nezgodno, neprijatno', 
		'komisch ' : 'komicno (ironicno)', 
		'der Berufverkehr ' : 'saobracaj u toku odlaska na/dolaska sa posla', 
		'schwindelig ' : 'vrtoglavica', 
		'das Geräusch ' : 'buka, zvuk', 
		'die Brücke ' : 'most', 
		'dauernd ' : 'stalno, konstantno', 
		'die Werkstatt ' : 'radionica', 
		'tanken ' : 'sipati gorivo', 
		'die Tankstelle ' : 'benzinska pumpa', 
		'umkehren ' : 'okrenuti (nesto staticno)', 
		'wenden ' : 'okrenuti (nesto u pokretu)', 
		'der Schokoriegel ' : 'cokoladna bar stanglica', 
		'die Beschwerde ' : 'zalba, primerdba', 
		'durch ' : 'kroz (+A)', 
		'um +A herum ' : 'okolo', 
		'bis zu +D ' : 'do', 
		'an +D vorbei ' : 'pored', 
	},
	'27.06.2016' : {
		'noch nie ' : 'jos ne', 
		'deshalb ' : 'zbog toga, stoga', 
		'bremsen ' : 'kociti', 
		'die Bremse ' : 'kocnica', 
		'einwandfrei ' : 'besprekorno', 
		'der Reifen ' : 'guma (od tocka)', 
		'verlängern ' : 'produzavati', 
		'glatt ' : 'glatko, ravno (eng. smooth)', 
		'-bar (sufix) +pridev ' : 'stanje vezano za to ...', 
		'    essen -> ess + bar -> essbar ' : 'jestivo', 
		'un- (prefix) ' : 'negiranje ...', 
		'    Das ist unmachbar ' : 'To je ne izvodljivo.', 
		'regelmäßig ' : 'ucestalo', 
		'überholen ' : 'preticati', 
		'die Panne ' : 'sitna nezgoda', 
		'vermeiden ' : 'izbeci', 
		'meiden ' : 'izbegavati', 
		'lahmlegen ' : 'obustavljen proces, onesposobiti', 
		'sperren ' : 'barikade, prepreka', 
		'die Bö ' : 'buka', 
		'strahlend ' : 'blistav, svetao (eng. glowing)', 
		'einweihen ' : 'svecano otvaranje', 
		'dichter ' : 'gust', 
		'verhindern ' : 'spreciti', 
		'ausweichen ' : 'izbeci nesto (fizicki)', 
	},
	'29.06.2016' : {
		'der Gehweg ' : 'trotoar', 
		'rücksichtslos ' : 'neobazriv, okrutan', 
		'die ...-ung (sufix) ' : 'sluzi za gradjenje abstraktnih pojmova ili propisa', 
		'bestimmen ' : 'odrediti', 
		'bestimmen (das Bestimmen) -> die Bestimmung ' : 'odlucnost', 
		'das Vorhaben ' : 'namera', 
		'    Wir haben ein Vorhaben ' : 'mi imamo nameru', 
		'    Wir haben vor ' : 'mi nameravamo', 
		'Wieso? ' : 'Zasto?, Kako to?', 
		'der Blick ' : 'pogled, panorama', 
		'spinnen ' : 'biti lud', 
		'wahnsinnig ' : 'lud', 
		'der Wahnsinn ' : 'ludost', 
		'tauchen ' : 'roniti', 
		'die Ausrüstung ' : 'oprema (eng. equipment) (generalno)', 
		'ausrüsten ' : 'opremiti', 
		'das Zelt ' : 'sator', 
		'verreisen ' : 'otputovati', 
		'ungerecht ' : 'nepravedno', 
		'aufs Land ' : 'na selo', 
		'die Wiederholung ' : 'ponavljanje', 
	},
	'04.07.2016' : {
		'die Insel ' : 'ostrvo', 
		'die Wüste ' : 'putsinja, pescara', 
		'das Seil ' : 'uze, konopac', 
		'das Reep ' : 'uze (pomorski izraz)', 
		'ich wündere mich warum? ' : 'pitami li se zasto? :)', 
		'die Unterkunft ' : 'smestaj', 
		'die Umgebung ' : 'okolina, okruzenje', 
		'herrlich ' : 'velicanstveno', 
		'beobachten ' : 'posmatrati', 
		'enttäuscht ' : 'razocaran', 
		'die Fähre ' : 'feri', 
		'verbringen (hat verbracht) ' : 'provesti', 
	},
	'06.07.2016' : {
		'der Kohl ' : 'kupus', 
		'das Ufer ' : 'recna obala, korito', 
		'der Umzug ' : 'selidba', 
		'der Deich ' : 'nasip (od zemlje)', 
		'die Geheimzahl ' : 'skriveni broj (pin)', 
		'abheben ' : 'podici (uopsteno)', 
		'beiliegend ' : 'prilozeno', 
		'sich merken ' : 'zapamtiti', 
		'merken ' : 'primetiti', 
		'sich einprägen ' : 'zapamtiti (urezati u mozak)', 
		'vernichten ' : 'unistiti', 
		'zerstören ' : 'unistiti', 
		'das Schreiben ' : 'dopis', 
		'das Mal ' : 'puta (matematicki)', 
		'    zwei mal drei ' : 'dva puta tri', 
		'nachsehen ' : 'proveriti (vizuelno)', 
		'die Sicherheit ' : 'sigurnost', 
		'klappen ' : 'poklopiti, uspeti (ideja)', 
		'küssen ' : 'ljubiti', 
		'+A + einfallen +D ' : 'setiti se, dosetiti se', 
		'heißen ' : 'zvati se, znaciti', 
		'weg sein ' : 'biti odsutan (eng. away)', 
	},
	'11.07.2016' : {
		'ob ' : 'da li?', 
		'bar bezahlen ' : 'gotovinsko placanje', 
		'bargeld ' : 'gotovina, kes', 
		'der Staat ' : 'drzava', 
		'die Bankverbindung ' : 'instrukcije za placanje', 
		'die Zinsen ' : 'kamata, interes', 
		'lassen (a -> ä) ' : 'pustiti, dozvoliti', 
		'nähen ' : 'krojiti', 
		'irgend(wie|wo|wann|was|...) ' : 'bilo (kako, gde, kada, sta), ikada', 
		'der Berater ' : 'savetnik', 
		'die Zukunft ' : 'buducnost', 
	},
	'13.07.2016' : {
		'der Biergarten ' : 'pivnica (na otvorenom)', 
		'der Betrag ' : 'kolicina (novca), suma, vrednost', 
		'der Daumen ' : 'palac', 
		'der Alptraum ' : 'nocna mora', 
		'feststellen ' : 'utvrditi, konstatovati', 
		'sämtliche ' : 'sve zajedno, svi', 
		'gelten (e->i) ' : 'vaziti (biti validno)', 
		'der Sturz ' : 'slobodan pad', 
		'der Dank ' : 'hvala', 
		'dankbar ' : 'zahvalan', 
		'dankbarkeit ' : 'zahvalnost', 
		'die Schuld ' : 'krivica', 
		'Lebensstationen ' : 'etape zivota', 
		'herein ' : 'napred', 
		'doof ' : 'blesav, glup', 
		'etwas vorhaben ' : 'preduzeti nesto', 
		'die Richtung ' : 'smer, put, ruta', 
		'erledigen +A ' : 'zavrsiti nesto', 
		'verachten ' : 'prezirati', 
		'ruhig sein ' : 'biti miran', 
		'die Puppe ' : 'lutka', 
		'der Stall ' : 'stala', 
	},
	'18.07.2016' : {
		'der Bart ' : 'brada', 
		'der Spitzname ' : 'nadimak', 
		'der Kosename ' : 'tepanje', 
	},
	'27.09.2016' : {
		'über nehmen ' : 'uzeti za zlo', 
		'ausstellen ' : 'pokazati, izlagati, izdati', 
		'die Ausstellung ' : 'izlozba', 
		'nah ' : 'blizu', 
		'fern ' : 'daleko', 
		'die Nähe ' : 'blizu, na dohvat ruke', 
	},
	'29.09.2016' : {
		'die Wildernis ' : 'divljina', 
		'die Haut ' : 'koza (organ)', 
		'das Leder ' : 'koza (materijal)', 
		'der Genuß ' : 'uzitak', 
		'genießen +A ' : 'uzivati', 
		'die Glühbirne ' : 'sijalica', 
		'daheim ' : 'kod kuce', 
		'vorbestellung ' : 'pre-order, rezervacija', 
		'der Hirsch ' : 'jelen', 
		'dsa Wirtshaus ' : 'gasthaus', 
		'schatte ' : 'senka', 
		'gehobene ' : 'fancy', 
		'der Anspruch /-˙˙e ' : 'ocekivanje, tvrdnja', 
		'edel ' : 'plemenit', 
		'unbezahlbar ' : 'neprocenjivo', 
		'schätzen ' : 'ceniti (to appreciate)', 
		'    Wert legen auf +A ' : 'schätzen', 
	},
	'04.10.2016' : {
		'das Märchen /- ' : 'bajka', 
		'die Gelegenheit ' : 'povod', 
		'schimpfen ' : 'psovanje', 
		'schreien ' : 'dranje, drati se', 
		'feuern ' : 'otkaz (sa polsa)', 
		'der Ober -> Herr Ober ' : 'kelner', 
		'der Gott /-˙˙er ' : 'bog', 
		'bunt ' : 'sareno', 
		'schießen (hat geschossen) ' : 'pucati', 
		'rechts ' : 'auf der rechten Seite', 
		'links ' : 'auf der linken Seite', 
	},
	'06.10.2016' : {
		'die Nähe ' : 'blizina', 
		'die Ferne ' : 'daljina', 
		'die Regierung ' : 'vlada', 
		'das Amt ' : 'ministarstvo', 
		'das Warnschild ' : 'znak upozorenja', 
		'sich zeigen ' : 'pokazati se', 
		'sogar ' : 'cak', 
		'berichten ' : 'izvestavati', 
		'verbringen ' : 'provoditi (vreme)', 
		'erst ' : 'tek (tek je ...)', 
		'zuerst ' : 'prvi (u nizu necega)', 
		'die Wiese ' : 'livada', 
		'befürchten ' : 'strahovati, bojati se', 
	},
	'24.02.2017' : {
		'notwendig ' : 'neophodno', 
		'hart ' : 'tvrdo, ozbiljno, tesko', 
		'das Gesicht ' : 'lice', 
		'der Kenner ' : 'poznavaoc', 
		'anderes ausgedrückt ' : 'drugacije receno', 
		'sich verhalten ' : 'ponasati se, ophoditi se', 
		'das Verhalten ' : 'ponasanje, maniri', 
		'schrecklich ' : 'uzasan', 
		'das Sprichwort ' : 'izreka', 
		'der Ausdruck ' : 'fraza, izreka, koncept', 
		'sich erkälten ' : 'prehladiti se', 
		'sich entschuldigen ' : 'izviniti se', 
		'nach meiner meinung ' : 'po mom misljenju', 
		'die Rüchfahrt ' : 'povratak', 
		'heben ' : 'podici', 
		'das Heben ' : 'podizati (doslovce)', 
		'der Herbst ' : 'jesen', 
		'der Sommer ' : 'leto', 
		'der Frühling ' : 'prolece', 
		'der Winter ' : 'zima', 
		'der Briefträger -er ' : 'postar', 
		'der Anwalt -e ' : 'advokat', 
		'das Getreide ' : 'grain (eng)', 
		'der Nebel ' : 'magla', 
		'der Gesetz -e ' : 'zakon', 
		'das Zelt -e ' : 'sator', 
		'schlagen ' : 'udarati, lupati', 
		'verreisen ' : 'odputovati', 
		'gewöhnlich ' : 'uobicajeno', 
		'das Mehl -e ' : 'brasno', 
	},
	'08.03.2017' : {
		'der Einwohner ' : 'stanovnik', 
		'Wer ' : 'ko?', 
		'Wem ' : 'kome?', 
		'Wen ' : 'koga?', 
		'weit ' : 'siroko, daleko', 
		'wie weite ' : 'koliko daleko / dokle', 
		'vorher ' : 'pre (ne zahteva nastavak - vreme)', 
		'nachher ' : 'posle (ne zahteva nastavak - vreme)', 
		'großzügig ' : 'velikodusan', 
		'kühl ' : 'sveze (vreme)', 
		'zuverlässig ' : 'poverljiv (karakterna osobina)', 
		'obwohl ' : 'iako', 
		'solange ' : 'sve dok', 
		'bevor ' : 'pre nego', 
		'damit ' : 'da se (gradi zavisnu recenicu)', 
		'der Makler ' : 'agent, broker, posrednik', 
		'die Einzehlheiten ' : 'pojedinosti', 
	},
	'16.03.2017' : {
		'der Dolmetscher ' : 'prevodioc ', 
		'die Dolmetscherin ' : 'prevodioc (zenski)', 
		'pflegen ' : 'starati se', 
		'die Stirn ' : 'celo', 
		'der Rumpf ' : 'torzo', 
		'die Wirbelsäule ' : 'kicma', 
		'die Zehe ' : 'palcevi', 
		'die Niere ' : 'bubreg', 
		'das Knie ' : 'koleno', 
		'der Hals ' : 'grlo', 
		'die Verdauung ' : 'varenje', 
		'die Schulter ' : 'rame', 
		'das Skelett ' : 'skelet', 
		'der Kreislauf ' : 'cirkulacija', 
		'der Bauch ' : 'stomak', 
		'der Magen ' : 'stomak (untra)', 
		'die Lunge ' : 'pluca', 
		'das Auge ' : 'oco', 
		'der Blutdruck ' : 'pritisak', 
		'das Geschlecht ' : 'pol', 
		'die Brust ' : 'grudi', 
		'das Gesäß ' : 'zadnjica', 
		'der Knochen ' : 'kosti', 
		'der Gehirn ' : 'mozak', 
		'das Ohr ' : 'uho', 
		'die Nase ' : 'nos', 
		'der Mund ' : 'usta', 
		'das Bein ' : 'noga', 
		'der Arm ' : 'ruka', 
		'der Atem ' : 'dah', 
		'das Sinnesorgan ' : 'cula (miris, dodir, vid, sluh, ...)', 
		'die Nahrung ' : 'negovati', 
		'zuführen ' : 'dati, podhraniti, dodati', 
		'das Merkmal ' : 'karakteristike', 
		'die Gestalt ' : 'oblik, figura, forma', 
		'feststellen ' : 'zakljuciti', 
		'erforschen ' : 'istrazivati', 
	},
	'20.03.2017' : {
		'schauen ' : 'gledati', 
		'die Fläche ' : 'povrsina', 
		'die Stätte ' : 'mesto (fizicki)', 
		'die Kraft ' : 'snaga, moc', 
		'das Arbeitsamt ' : 'sluzba za zaposljavanje', 
		'die Bedingung ' : 'preduslov', 
		'das Arbeitsverhältnis ' : 'radni odnos', 
		'der Vertrag ' : 'ugovor', 
		'der Lohn ' : 'plata', 
		'der Arbeitsunfall ' : 'nesreca na poslu', 
		'der Gang ' : 'tok', 
		'die Arbeitsunfähigkeit ' : '(eng. sick leave, inability to work)', 
		'der Zwerg ' : 'patuljak', 
		'die Absicht ' : 'namera', 
		'das Elend == die Not ' : '(in need, hardship, misery)', 
		'der Neid ' : 'ljubomora', 
		'neidisch ' : 'ljubomoran', 
		'der Eigennutz ' : 'egoizam', 
		'die Mühe ' : 'trud', 
		'der Befehl ' : 'naredba', 
		'der Auftrag ' : 'naredba', 
		'die Meinung ' : 'misljenje', 
		'kräftig ' : 'snazan, mocan', 
		'die Gegend ' : 'okolina', 
		'das Misstrauen ' : 'nepoverenje, sumnja', 
		'der Zweifel ' : 'sumnja', 
		'das Vergnügen ' : 'zadovoljstovo', 
		'die Verzeihung ' : 'oprost', 
		'bedinen ' : 'usluziti', 
		'die Bedienung ' : 'usluga', 
	},
	'22.03.2017' : {
		'sich bemühen ' : 'potruditi se', 
		'beabsichtigen ' : 'nameravati', 
		'sich entschließen ' : 'odluciti se', 
		'gelingen ' : 'uspevati', 
		'der Taugenichts ' : 'lezilebovic', 
		'versprechen ' : 'obecati', 
		'vorhaben ' : 'nameravati', 
		'anzulegen ' : 'zakaciti se (fizicki)', 
		'sich weigern ' : 'neposlusnost', 
		'bestanden ' : 'poloziti', 
	},
	'23.03.2017' : {
		'die Bruchzahl / -en ' : '(eng. fraction numbers)', 
		'ein Drittel ' : '1/3', 
		'ein Viertel ' : '1/4', 
		'ein Fünftel ' : '1/5', 
		'zwei Drittel ' : '2/3', 
		'das Jahrzehnt ' : 'decenija', 
		'das jahrhuntert ' : 'stolece', 
		'tagsüber ' : 'preko dana', 
		'die Mitternacht ' : 'ponoc', 
		'in der Früh (österreich) ' : 'ujutro', 
		'reife ' : 'frische', 
		'    reife Apfel ' : 'zrela jabuka', 
		'die Butter ' : 'maslac', 
		'der Quark ' : 'jogurt-pavlaka', 
		'roh ' : 'sirovo (eng. raw)', 
		'die Rohkost ' : 'sirovo voce i povrce', 
		'die Unterhaltung ' : 'razgovora', 
		'die Verfügung ' : 'raspolozivost', 
		'die Gegen ' : 'okolina', 
		'die Bank ' : 'klupa, banka', 
		'der Abfall == der Müle ' : 'smece', 
		'der Genuss ' : 'ukus', 
		'das Gefengnis ' : 'zatvor', 
		'der Gewinn ' : 'dobitak', 
		'die Rede ' : 'govor', 
		'die Wärme ' : 'toplota', 
		'die Kälte ' : 'hladnoca', 
		'das Gebäude ' : 'zgrada', 
		'die Vorstellung ' : 'prestava', 
		'das Erlaubnis / -se ' : 'dozvola', 
	},
}; 
