const words = { 
'machen ' : 'ciniti, raditi', 
'arbeiten ' : 'raditi', 
'heißen ' : 'zvati se', 
'essen ' : 'jesti', 
'lessen ' : 'citati', 
'fahren ' : 'voziti', 
'laufen ' : 'trcati, setati', 
'sein ' : 'biti', 
'sagen ' : 'reci, kazati', 
'ordnen ' : 'rasporediti', 
'(Herzlich) Willkommen ' : '(Srdacno) Dobrodosli', 
'bitte ' : 'molim', 
'Freut mich ' : 'drago mi je', 
'die Stadt ' : 'grad', 
'die Hauptstadt ' : 'glavni grad', 
'der Unterschied ' : 'razlika', 
'der Schüler ' : 'djak', 
'der Lerner ' : 'ucenik', 
'der Stadtführer ' : 'gradski vodic', 
'der Spaß ' : 'zabava', 
'die Straße ' : 'ulica', 
'das Gegenteil ' : 'suprotnost', 
'lesen ' : 'citati', 
'schreiben ' : 'pisati', 
'der Gegenstand ' : 'predmet (fizicki)', 
'Wer ' : 'ko?', 
'Was ' : 'sta?', 
'Wo ' : 'gde?', 
'Woher ' : 'odakle?', 
'Wohin ' : 'kuda?', 
'Wann ' : 'kada?', 
'Wie ' : 'kako?', 
'drehen ' : 'listati', 
'ergänzen ' : 'dopuniti', 
'Satzzeichen ' : '? , . ; :', 
'der Wasserhahn ' : 'cesma', 
'lernen ' : 'uciti', 
'lehren ' : 'poducavati', 
'überspringen ' : 'preskociti', 
'springen ' : 'skociti', 
'das Gespräch ' : 'razgovor', 
'unbekannte ' : 'nepoznato', 
'Buchstaben ' : 'slovo', 
'bedeuten ' : 'znaciti', 
'Entschuldigung ' : 'izvinite', 
'buchstabieren ' : 'spelovati', 
'da ' : 'tu (mesto)', 
'Vorname ' : 'Name', 
'Familienname ' : 'Nachname', 
'Land ' : 'zemlja (tlo)', 
'die Folge ' : 'epizoda', 
'das Bild ' : 'slika', 
'bereit ' : 'spreman', 
'meinen ' : 'misliti (stav)', 
'hübsch ' : 'lepa (najcesce za zene)', 
'schön ' : 'hübsch', 
'wohnen ' : 'stanovati', 
'leben ' : 'ziveti', 
'der Tee ' : 'caj', 
'der Kaffee ' : 'kafa', 
'der Moment ' : 'trenutak', 
'die Eltern ' : 'roditelji', 
'die Mutter ' : 'majka', 
'der Vater ' : 'otac', 
'die Großmutter ' : 'baka', 
'die Schwester ' : 'sestra', 
'der Bruder ' : 'brat', 
'die Geschwister ' : 'eng. siblings (brat i sestra, brat i brat, sestra i sestra)', 
'groß ' : 'veliko', 
'klein ' : 'malo', 
'die Übung ' : 'vezba', 
'sagen ' : 'reci, kazati', 
'hier ' : 'ovde', 
'da ' : 'tu', 
'dort ' : 'tamo', 
'Ihnen ' : 'Vama', 
'Dir ' : 'tebi', 
'müde ' : 'umoran', 
'erholten ' : 'odmoran', 
'öffnen ' : 'otvoriti', 
'offen ' : 'otvoren', 
'der Abschnitt ' : 'sekcija, odsek', 
'das Kind ' : 'dete', 
'der Lehrer ' : 'ucitelj', 
'der Lerner ' : 'ucenik', 
'der Sohn / die Söhne ' : 'sin / sinovi', 
'die Tochter ' : 'kcerka', 
'das Rätsel ' : 'zagonetka', 
'die Zahlen ' : 'brojevi', 
'die Zahl ' : 'broj', 
'zahlen ' : 'platiti', 
'die Nummer ' : 'broj', 
'bezahlen ' : 'platiti (odmah)', 
'die Lösung ' : 'resenje', 
'Liegen ' : 'lezati', 
'verheiratet ' : 'vencan / a', 
'geschieden ' : 'razveden / a', 
'haben ' : 'imati', 
'alt ' : 'staro', 
'jung ' : 'mlado', 
'die Heimatland ' : 'domovina, zemlja porekla', 
'der Ort ' : 'mesto', 
'der Wohnort ' : 'prebivaliste', 
'Familienstand ' : 'bracno stanje', 
'ledig ' : 'neozenjen, posle 18g (eng. single)', 
'verwitwet ' : 'udovac / ica', 
'die Witwe ' : 'udovica', 
'der Witwer ' : 'udovac', 
'der Herr ' : 'gospodin', 
'die Frau ' : 'gospodja', 
'der Titel ' : 'naslov', 
'Sich vorstellen ' : 'predstaviti se', 
'viele ' : 'mnogo', 
'das Baby ' : 'beba', 
'der Freund ' : 'prijatelj', 
'die Freundin ' : 'prijateljica', 
'leider ' : 'nazalost', 
'es tut mir leid ' : 'zao mi je', 
'König ' : 'kralj', 
'lang ' : 'dugo', 
'kurz ' : 'kratko', 
'gegenteil ' : 'suprotnost', 
'die Seite ' : 'strana', 
'passen ' : 'biti taman', 
'zeigen ' : 'pokazati', 
'an kreuzen ' : 'obeleziti, markirati', 
'auf füllen ' : 'popuniti', 
'der Mensch / -en (pl) ' : 'covek, ljudi (pl)', 
'der Apfel ' : 'jabuka', 
'die Erde ' : 'zemlja (zemljiste, materijal)', 
'der Markt ' : 'pijaca', 
'folgen ' : 'pratiti', 
'die Folge ' : 'epizoda', 
'brauchen ' : 'potreban ( eng. need )', 
'das Problem ' : 'problem', 
'wie viel? ' : 'koliko?', 
'das Kilo ' : 'kilo', 
'das Obst ' : 'voce', 
'junger Mann ' : 'mladic', 
'sonst noch etwas ' : 'inace jos nesto', 
'sonst ' : 'inace', 
'noch ' : 'jos', 
'etwas ' : 'nesto', 
'vielleicht ' : 'mozda', 
'kosten ' : 'kostati', 
'die Kosten ' : 'troskovi', 
'gern(e) ' : 'rado', 
'das Wort / - en ' : 'rec', 
'die Wörten ' : 'reci', 
'das Lebensmittel ' : 'namirnice', 
'Nennen ' : 'imenovati', 
'das Brötchen ' : 'kifla, zemicka, pecivo', 
'bisschen ' : 'ugriz', 
'der Biss ' : 'ujed, ugriz, zalogaj', 
'schauen ' : 'gledati', 
'sehen ' : 'videti', 
'der Kuchen ' : 'kolac', 
'die Tomate ' : 'paradajz', 
'der Ort / -e (pl) ' : 'mesto', 
'der Korb / -e (pl) ' : 'korpa', 
'im ' : 'unutra', 
'der Fisch / -e (pl) ' : 'riba', 
'die Traube / -en (pl) ' : 'grozdje', 
'der Saft / -e (pl) ' : 'sok', 
'die Säfte ' : 'sokovi', 
'drehen ' : 'okrenuti', 
'der Zettel ' : 'cedulja', 
'alles ' : 'sve', 
'nichts ' : 'nista', 
'der Sahne ' : 'slag', 
'die Brille ' : 'naocare', 
'die Birne ' : 'kruska', 
'vergleichen ' : 'porediti', 
'gleich ' : 'isto (eng. same)', 
'das Beispiel ' : 'primer', 
'die Anmeldung ' : 'prijava', 
'das Gewicht ' : 'masa', 
'die Maß ' : 'mera', 
'die Maßeinheiten ' : 'merna jedinica', 
'die Einheit ' : 'jedinica (u bilo kom obliku)', 
'die Abteilung ' : 'odeljak, odsek', 
'das Angebote ' : 'ponuda', 
'sonder ' : 'specijalna, posebna', 
'oben ' : 'gore', 
'unten ' : 'dole', 
'mitte ' : 'u sredini', 
'links ' : 'levo', 
'rechts ' : 'desno', 
'die Null ' : 'nula', 
'komma ' : 'zarez', 
'das Öl ' : 'ulje', 
'die Flasche ' : 'boca, flasa', 
'die Packung ' : 'pakovanje', 
'das Rind ' : 'govece', 
'die Kuh ' : 'krava', 
'der Bulle / der Stier ' : 'vo, bik', 
'die Rindfleich ' : 'govedina', 
'die Dose ' : 'konzerva', 
'die Dosis ' : 'mera (leka)', 
'der Becher ' : 'mala posuda, iskljucivo od plastike (casa za jogurt, ...)', 
'essen ' : 'jesti', 
'das Esse ' : 'jelo', 
'lieblings ' : 'omiljeni', 
'der Liebling ' : 'miljenik', 
'der Film ' : 'film', 
'die Soße ' : 'sos', 
'das Hähnchen ' : 'piletina', 
'der Durst ' : 'zedan', 
'der Hunger ' : 'gladan', 
'mögen ' : 'svidjati, gotiviti (eng. like)', 
'lieben ' : 'voleti (strastveno)', 
'schmecken ' : 'osecati ukus', 
'der Geschmack ' : 'ukus (generano)', 
'Vorsicht! ' : 'pazi', 
'die Vorsicht ' : 'paznja, obazrivost', 
'vorsichtig ' : 'obazriv', 
'das Zimmer ' : 'prostorija, soba', 
'Wohnzimmer ' : 'dnevna soba', 
'der Stock ' : 'sprat', 
'die Möbel (pl) ' : 'namestaj', 
'das Möbelstück ' : 'komad namestaja', 
'der Schritt ' : 'korak', 
'die Schritte ' : 'koracati', 
'kennen ' : 'poznavati ( mesto ili vestina )', 
'weiter ' : 'dalje', 
'teuer ' : 'skupo', 
'billig ' : 'jeftino', 
'der Einfall ' : 'dosetka, ideja', 
'die Idee ' : 'ideja (internacionalno)', 
'machen ' : 'ciniti, raditi', 
'noch ' : 'jos', 
'unmöglich ' : 'nemoguce', 
'gerfallen ' : 'dopadati se (gotiviti)', 
'finden ' : 'naci (gotiviti)', 
'gut ' : 'dobro', 
'schlecht ' : 'lose (kvalitet)', 
'schlimm ' : 'lose (situacija)', 
'böse    ' : 'zlo, lose (moralno, eticki)', 
'verrückt ' : 'iscasen, poremecen', 
'seltsam ' : 'neobicno, cudno', 
'höflich ' : 'ljubazan, uctiv', 
'freundlich ' : 'prijatan', 
'der Flur ' : 'hodnik', 
'laut ' : 'glasno', 
'leise ' : 'tiho', 
'wirklich ' : 'stvarno, zaista', 
'das Haus ' : 'kuca', 
'breit ' : 'siroko', 
'schmal ' : 'usko', 
'schön ' : 'lepo', 
'hässlich ' : 'ruzno', 
'hell ' : 'svetlo', 
'dunkel ' : 'tamno', 
'zwichen ' : 'izmedju, medju', 
'vergleichen ' : 'uporediti', 
'das Ratespiel ' : 'igra pogadjanja', 
'aber ' : 'vrlo, veoma, bas, ali', 
'die Dusche ' : 'tus', 
'das Bett ' : 'krevet', 
'das Wasschbecken ' : 'lavabo', 
'der Schrank ' : 'ormar', 
'der Kühlschrank ' : 'frizider', 
'der Herd ' : 'sporet, rerna', 
'die Badewanne ' : 'kada', 
'der Fernseher ' : 'televizor', 
'die Spühle ' : 'sudopera', 
'das Gerät ' : 'uredjaj, stroj, masina', 
'grün ' : 'zelena', 
'gelb ' : 'zuta', 
'grau ' : 'siva', 
'anzeigen ' : 'oglasi', 
'der Preis ' : 'cena, nagrada', 
'preiswert ' : 'jeftin', 
'mieten ' : 'onaj koji zakupljuje (stanar)', 
'vermieten ' : 'onaj koji daje u najam (vlasnik)', 
'die Miete ' : 'izdavati', 
'das Praktikum ' : 'praksa', 
'die Praxis ' : 'ordinacija', 
'möbliert ' : 'namesten', 
'die Zeit ' : 'vreme (u kontekstu sata)', 
'das Wetter ' : 'vreme (u kontekstu vremenske prognoze)', 
'voll ' : 'puno', 
'leer ' : 'prazno', 
'der Raum ' : 'prostor', 
'die Lage ' : 'stanje, leziste, situirano', 
'die Woche ' : 'sedmica', 
'ruhig ' : 'mirno', 
'die Ruhe ' : 'mir (spokoj)', 
'neben ' : 'pored (uopsteno)', 
'Nebenkosten ' : 'sporedni troskovi', 
'sitzt ' : 'sedeti', 
'jetzt ' : 'sada', 
'sofort ' : 'odmah', 
'dringend ' : 'hitno, vazno', 
'warm ' : 'toplo', 
'kalt ' : 'hladno', 
'die Ferien ' : 'raspust', 
'der Urlaub ' : 'odmor', 
'der Stern ' : 'zvezda', 
'das Zeichen ' : 'znak', 
'glauben ' : 'verovati', 
'antworten ' : 'odgovoriti (usmeno, pismeno,...)', 
'helfen ' : 'pomoci', 
'möchten ' : 'zeleti (eng. wish)', 
'Sternzeichen ' : 'horoskop', 
'an ' : 'na (predlog)', 
'Steinbock ' : 'jarac', 
'gemütliches ' : 'udobno', 
'vor allem ' : 'pre svega', 
'knallrotes ' : 'drecavo crvena', 
'besonders gern ' : 'posebno drago/draga', 
'Welche ' : 'koja, koji', 
'lecker ' : 'ukusno', 
'einrichten ' : 'uredjen', 
'der Knall ' : 'eksplozija', 
'der Wunsch ' : 'zelja (u bukvalnom smislu)', 
'wünschen ' : 'zeleti', 
'die Gemütlichkeit ' : 'udobno', 
'das Herz ' : 'srce', 
'der Bahnhof ' : 'zeleznicka stanica', 
'der Stift ' : 'pisljka (olovka)', 
'der Shal ' : 'sal', 
'die Jacke ' : 'jakna', 
'schon ' : 'vec, bas', 
'der Tag ' : 'dan', 
'genug ' : 'dovoljno, dosta', 
'die Sprache ' : 'jezik', 
'sprechen ' : 'pricati', 
'aufstehen ' : 'ustati', 
'aufräumen ' : 'pospremiti', 
'stimmt ' : 'tako je', 
'einkaufen ' : 'kupovati', 
'kaufen ' : 'kupiti', 
'kochen ' : 'kuvati', 
'frühstücken ' : 'doruckovati', 
'das Frühstück ' : 'dorucak', 
'fernsehen ' : 'gledati televiziju', 
'der Fernseher ' : 'televizor', 
'lustig ' : 'smesno', 
'ernst ' : 'ozbiljno', 
'traurig ' : 'tuzno', 
'langweilig ' : 'dosadan', 
'doof ' : 'simpaticno glupo', 
'dumm ' : 'neutralno glupo', 
'blöd ' : 'glup (uvredljivo)', 
'nett ' : 'fino, ljubazno (eng. nice)', 
'lachen ' : 'smejati se', 
'geben ' : 'dati, postojati ... (e -> i)', 
'spät ' : 'kasno', 
'früh ' : 'rano', 
'der Zeiger ' : 'kazaljka', 
'der Vollidiot ' : 'potpuni idiot', 
'die Uhr ' : 'sat (masina, rucni sat, ... eng. watch)', 
'die Stunde ' : 'cas (60 min ... eng. hour)', 
'vorspielen ' : 'odsvirati', 
'verbinden ' : 'povezati', 
'zu spät kommen ' : 'zakasniti', 
'aufräumen ' : 'pospremiti', 
'anrufen ' : 'pozvati (telefonom)', 
'aufstehen ' : 'ustati', 
'stehen ' : 'stajati', 
'fernsehen ' : 'gledati tv', 
'drehen ' : 'okretati', 
'umdrehen ' : 'okrenuti (jednom)', 
'die Sonne ' : 'sunce', 
'der Mittag ' : 'podne', 
'der Vormittag ' : 'pre podne', 
'der Nachmittag ' : 'posle podne', 
'der Morgen ' : 'jutro, sutra', 
'heute ' : 'danas', 
'der Abend ' : 'vece', 
'die Nacht ' : 'noc', 
'am ' : '(eng. in)', 
'in der Nacht ' : 'tokom noci', 
'von ' : 'od', 
'bis ' : 'do', 
'am ' : 'dane u sedmici i/ili doba dana', 
'um ' : 'kod satnice', 
'die Schicht ' : 'smena, sloj', 
'jeden Tag ' : 'svakog dana', 
'jeden ' : 'svaki', 
'jede ' : 'savi', 
'Öffnungszeit / -en ' : 'radno vreme', 
'der Depp ' : 'debil od milosti', 
'das Joggen ' : 'dzogiranje', 
'zwei mal ' : 'dva puta', 
'mal ' : 'puta (npr. koliko puta)', 
'traiben ' : 'terati (osobu, stoku)', 
'Sport treiben ' : 'baviti se sportom', 
'fechten ' : 'macevanje', 
'auch ' : 'isto, takodje', 
'mitkommen ' : 'doci sa nekim', 
'der Wetter ' : 'vreme', 
'regnen ' : 'pada kisa', 
'der Regen ' : 'kisa', 
'scheinen ' : 'sijati, ciniti se', 
'die Lust ' : 'volja', 
'Lust haben ' : 'imati volju, biti u fazonu', 
'das Schloss ' : 'zamak, brava (mehanizam)', 
'der Schuh/ -e ' : 'obuca, cipela', 
'der Anzug/ - ˚˚ e ' : 'odeca, odelo', 
'das Geld ' : 'novac', 
'Mach nicht ' : 'nema veze', 
'schnell ' : 'brzo', 
'langsam ' : 'sporo', 
'öft ' : 'ucestalo', 
'selten ' : 'retko', 
'aufrufen ' : 'prozvati', 
'anrufen ' : 'pozvati (telefonom)', 
'weitermachten ' : 'nastaviti (dalje sa radom)', 
'der Laden ' : 'radnja', 
'das Geschäft ' : 'eng. bussiness', 
'vielleicht ' : 'mozda', 
'der Quatsch ' : 'besmislica (eng. nonesense)', 
'der Obstladen ' : 'prodavnica voca', 
'der Wind ' : 'vetar', 
'windig ' : 'vetrovito', 
'warm ' : 'toplo', 
'kalt ' : 'hladno', 
'schneien ' : 'snezi, pada sneg', 
'der Schnee ' : 'sneg', 
'bewölkt ' : 'oblacno', 
'die Wolke ' : 'oblak', 
'Norden ' : 'sever', 
'Süden  ' : 'jug', 
'Westen ' : 'zapad', 
'Osten  ' : 'istok', 
'das Kraut ' : 'biljka', 
'die Jahreszeiten ' : 'godisnja doba', 
'der Satz / -˚˚e ' : 'recenica', 
'gucken ' : 'gledaj, baci pogled', 
'nehmen ' : 'uzimati ... ( e -> i )', 
'heiß ' : 'vrelo (vruce)', 
'dabai haben ' : 'imati sa sobom nesto', 
'Gesundheit ' : 'ziv bio, zdrav bio', 
'doch ' : 'potvrdan odgovor na negativno pitanje (jedno od znacnja)', 
'möchten ' : 'zeleti', 
'gar ' : 'uopste', 
'toll ' : 'sjajno, bajno', 
'der Tanz ' : 'ples', 
'tanzen ' : 'plesati', 
'wollen ' : 'zeleti, hteti (situacija)', 
'möchten ' : 'zeleti, hteti (stvari, predmet ... uctiviji oblik)', 
'können ' : 'moci', 
'los sein ' : 'desava se', 
'los ' : 'ajde', 
'jeder ' : 'svako', 
'jede  ' : 'svaka', 
'jedes ' : 'svaki', 
'klar ' : 'jasno', 
'nie ' : 'nikada', 
'noch nie ' : 'nikada nisam ...', 
'erklären ' : 'objasniti', 
'anfangen ' : 'pocinjati (opsti oblik)', 
'starten  ' : 'pocinjati (vazi sa masine, ...)', 
'beginnen ' : 'pocinjati (vazi za odredjeni proces)', 
'fangen ' : 'uhvatiti', 
'üben ' : 'vezbati', 
'über ' : 'iznad', 
'das Team ' : 'tim', 
'die Mannschaft ' : 'tim', 
'singen ' : 'pevati', 
'reiten ' : 'jahati', 
'handstand machen ' : 'stajati na rukama', 
'der Löffel ' : 'kasika', 
'eintragen ' : 'unosenje podataka', 
'tragen ' : 'nositi', 
'das Getränk / -e ' : 'pice', 
'der Unterricht ' : 'predavanje', 
'tun ' : 'ciniti, delovati, raditi (eng. do)', 
'der Tipp / -s ' : 'savet', 
'nur ' : 'samo', 
'das Trinkgeld ' : 'napojnica', 
'die Zeitschrift ' : 'casopis', 
'die Sendung / -en ' : 'emisija', 
'senden ' : 'emitoavti, poslati', 
'das Beispiel ' : 'primer', 
'Beruf ' : 'zanimanje', 
'scheinen ' : 'ciniti se, sijati', 
'es scheint so ' : 'cini se tako', 
'kann sein, kann nicht sein ' : 'moze bit, a ne mora', 
'los ' : 'ajde', 
'drenen ' : 'okrenuti', 
'Tu nicht so! ' : 'ne budi takav!', 
'seit ' : 'od (eng. since)', 
'aufhören ' : 'zaustaviti se, prestati, stati (opsti oblik)', 
'stoppen ' : 'zaustaviti se, prestati, stati (vozilo)', 
'krank ' : 'bolestan', 
'gesund ' : 'zdrav', 
'der Unsinn ' : 'glupost (eng. nonsense)', 
'verkaufen ' : 'prodavati', 
'der Verkaufer ' : 'prodavac', 
'die Blume / -n ' : 'cvet', 
'die Unterschrift / -en ' : 'potpis', 
'sich erinnern ' : 'prisetiti se', 
'der Schauspieler ' : 'glumac', 
'spielen ' : 'igrati, svirati, glumiti', 
'wütend ' : 'besan', 
'die Wut ' : 'bes', 
'liefern ' : 'isporuciti, dostaviti', 
'bringen ' : 'doneti', 
'Exportkaufmann (m) ' : 'izvoznik', 
'Exportkauffrau (f) ' : 'izvoznik', 
'Seit wann? ' : 'od kada?', 
'Wann haben Sie angefangen? ' : 'kada ste poceli?', 
'Vor fünf Wochen ' : 'pre 5 nedelja', 
'Wie lange? ' : 'Koliko dugo?', 
'Bewerbung ' : 'propratno pismo (eng. application form)', 
'Sehr geehrter ' : 'postovani', 
'Wirtschaf ' : 'privreda', 
'nächstes ' : 'sledeca', 
'zur Verfügung stehen ' : 'stojim Vam na raspolaganju', 
'als ' : 'kao', 
'der Beruf ' : 'zanimajne', 
'die Ausbildung ' : 'obuka', 
'die Geschichte ' : 'istorija, prica', 
'Ledenschaft ' : 'strast (eng. passion)', 
'wieder ' : 'ponovo', 
'die Börse ' : 'berza', 
'gerade ' : 'upravo, sada', 
'gibt es ' : 'ima li, postoji li', 
'geben ' : 'postojati, dati (e -> i)', 
'enden ' : 'zavrsiti se, prestati', 
'Mitte + <mesec> ' : 'sredinom meseca', 
'früher ' : 'ranije', 
'später ' : 'kasnije', 
'fertig ' : 'gotovo', 
'wenig ' : 'malo, nekoliko', 
'im <mesec> ' : 'koristi se uz mesec', 
'für ' : 'za, na ( uz vremenske odrednice )', 
'der Gedanke / -n ' : 'misao', 
'die Branche ' : 'ogranak, bransa', 
'die Kenntniss ' : 'umece, znanje ( eng. knowhow )', 
'die Dauer ' : 'trajanje', 
'die Vereinbarung ' : 'dogovor', 
'Schwerpunkt ' : 'fokus', 
'erforderlich ' : 'potrebno', 
'benötigt ' : 'potrebno', 
'Führerschein ' : 'vozacka dozvola', 
'die Bildung ' : 'obrazovanje', 
'mindestens ' : 'najmanje, makar', 
'bewerben ' : 'prijaviti se', 
'betragen ' : 'iznositi (generalno)', 
'Ungewöhnliche ' : 'neobicno', 
'fremden ' : 'nepoznat', 
'dürfen ' : 'smeti', 
'darf ich? ' : 'smem li?', 
'echt ' : 'pravo, prirodno', 
'künstlich ' : 'vestacko', 
'sicher ' : 'sigurno', 
'setzen ' : 'sedati (gl)', 
'sitzen ' : 'sedeti (stanje)', 
'gemütlich ' : 'udobno', 
'Gemütlichkeit ' : 'lagodnost, opustenost (vazi za juzni deo Nemacke)', 
'die Lederhose ' : 'tregerice (m)', 
'der Dirndl ' : 'zenska tradicionalna nosnja (f)', 
'das Meer / -e ' : 'more', 
'Schade ' : 'steta', 
'schaffen ' : 'zavrsiti, dovesti do kraja', 
'der Traum ' : 'san', 
'pflegen ' : 'negovati, starati se o necemu', 
'draußen ' : 'napolju', 
'beide ' : 'oboje, bilo koji (eng. both)', 
'füttern ' : 'hraniti (decu, zivotinje, ...)', 
'der Puppenspieler ' : 'lutkar', 
'das Stück / -e ' : 'komad, prestava', 
'der Kunde / -n ' : 'musterija', 
'die Hochzeit / -en ' : 'vencanje', 
'kennen lernen ' : 'upoznati', 
'bekommen ' : 'dobiti', 
'die Ratschläge ' : 'saveti', 
'der Ratschlag ' : 'savet', 
'unbedingt ' : 'nuzno, neophodno', 
'der Dom ' : 'katedrala, hram', 
'hingehen ' : 'otici tamo', 
'Langsam, aber sicher ' : 'Polako, ali sigurno', 
'der Ausflug ' : 'izlet', 
'das Märchen ' : 'bajka', 
'der Honig ' : 'med', 
'die Kasse ' : 'kasa', 
'das Ziel / -e ' : 'cilj, odrediste', 
'auswählen ' : 'izabrati', 
'der Preis / -e ' : 'nagraditi, cena', 
'schieben ' : 'gurati', 
'einschieben ' : 'ugurati', 
'das Wechselgeld ' : 'kusur', 
'stempeln ' : 'overiti, ponistiti', 
'Man ' : '>> bezlicni oblik (eng. One)', 
'    Man muss die Fahrkarte bezahlen ' : 'karta se mora kupiti', 
'    Man bezahlt die Fahrkarte       ' : 'karta se placa', 
'immer ' : 'uvek', 
'Dann ' : 'potom, onda', 
'dürfen ' : 'smeti', 
'parken ' : 'parkirati', 
'erlauben ' : 'dozvoljeno', 
'verboten ' : 'zabranjeno', 
'Das Schield ' : 'znak (saobracajni)', 
'der Schield ' : 'viteski stit', 
'mitnehmen ' : 'poneti sa sobom', 
'ruhig gelegen ' : 'miran kraj', 
'übernachtung ' : 'prenociste', 
'übermorgen ' : 'prekosutra', 
'bleiben ' : 'ostati', 
'der Ausweis ' : 'licna karta', 
'abgeben ' : 'predati', 
'Das Gepäck ' : 'prtljag', 
'vergessen ' : 'zaboraviti', 
'eintritt ' : 'ulazak', 
'Turmbesteigungen ' : 'penjanje', 
'berühmte ' : 'poznato', 
'der Tempel ' : 'hram', 
'Sehenswürdigkeit ' : 'znamenitost', 
'der Tod ' : 'smrt', 
'tot ' : 'mrtav', 
'krank sein ' : 'biti bolestan', 
'um was geht es? ' : 'o cemu se radi?', 
'husten ' : 'kasljati', 
'aussehen ' : 'izgledati', 
'das Aussehen ' : 'izgled', 
'das Auge / -n ' : 'oko / oci', 
'zeigen ' : 'pokazati', 
'entzündet ' : 'upaljeno ( pod upalom )', 
'geschwollen ' : 'oteceno', 
'weh tut ' : 'boleti', 
'versuchen ' : 'pokusati, probati', 
'in der Nähe ' : 'blizu, na dohvat ruke (eng. nearby, close by)', 
'selbst ' : '(eng. self)', 
'gefährlich ' : 'opasan', 
'untersuchen ' : 'pregledati', 
'vorsichtig ' : 'pazljivo', 
'genau untersuchen ' : 'temeljno pregledati', 
'das Haar ' : 'dlaka, kosa', 
'der Kopf ' : 'glava', 
'die Lippen ' : 'usne', 
'der Mund ' : 'usta', 
'der Hals ' : 'vrat, grlo', 
'der Rücken ' : 'ledja', 
'die Zehn ' : 'prsti na nogama', 
'der Zeh ' : 'prst na nozi', 
'der Fuß ' : 'stopalo', 
'der Bauch ' : 'trbuh', 
'die Zunge ' : 'jezik', 
'gegen ' : 'protiv', 
'der Schmerz ' : 'bol (dusevna)', 
'die Schmerzen ' : 'bol (fizicka)', 
'der Vernichtungsschmerz ' : 'izrazito jak bol', 
'die Vernichten ' : 'unistiti', 
'das Hemd ' : 'majica', 
'sollen ' : 'trebati (trebalo bi)', 
'rasu ' : 'napolje', 
'vereinbaren ' : 'zakazati, ugovoit, dogovoriti', 
'ändern ' : 'promeniti', 
'absagen ' : 'otkazati', 
'der Turm ' : 'toranj', 
'täglich ' : 'svakodnevno, svaki dan', 
'bieten ' : 'nuditi', 
'Freude ' : 'radost, sreca', 
'Reiten ' : 'jahati', 
'Treffpunkt ' : 'mesto sastajanja', 
'Entspannung ' : 'opustanje, relaksacija', 
'der Betreff ' : '(eng. subject)', 
'die Anrede ' : 'pozdrav', 
'der Empfänger ' : 'primaoc', 
'Reiterhof ' : 'ergela, konjusarnica', 
'anbieten ' : 'ponuditi', 
'werden ' : 'postati (eng. become)', 
'Entspannen ' : 'opustiti se', 
'genießen ' : 'uzivati', 
'vor Ort ' : 'na licu mesta', 
'das Obst ' : 'voce', 
'die Frucht /-˚˚e ' : 'vocka (jedna)', 
'wahr ' : 'tacno, istinito', 
'dick ' : 'debelo', 
'einladen ' : 'pozvati', 
'leider ' : 'nazalost', 
'jemand ' : 'neko', 
'unterwegs ' : 'usput, biti na putu (kretati se)', 
'fremde ' : 'nepoznato', 
'hafen ' : 'luka', 
'abholen ' : 'pokupit', 
'das Heft / -e ' : 'sveska / e', 
'backen ' : 'peci', 
'der Bäcker ' : 'pekar', 
'die Bretzel ' : 'pereca', 
'die Bäckerei ' : 'pekara', 
'aufpassen (hat aufgepasst) ' : 'obratiti paznju', 
'achten ' : 'obratiti paznju ( pozornost )', 
'eigentlich ' : 'zapravo', 
'weinen ' : 'plakati', 
'zuerst ' : 'prvo', 
'allein ' : 'sam / sama / samo', 
'verlieren ' : 'izgubiti', 
'geradeaus ' : 'pravo (smer)', 
'einfach ' : 'jednostavno', 
'unten ' : 'dole', 
'passieren ' : 'dogoditi se', 
'gleich ' : 'odmah, isto (zavisi od konteksta)', 
'der Bahnhof ' : 'zeleznicka stanica', 
'die Post ' : '', 
'die Metzgerei ' : 'mesara', 
'zu Fuß ' : 'peske', 
'mit +D ' : 'I (u srpskom)', 
'das Messer ' : 'noz', 
'das Flugzeug / -e ' : 'avion', 
'der Verker ' : 'saobracaj, sex', 
'der Flughafen / -˚˚ ' : 'aerodrom', 
'der Straußenverker ' : 'ulicni saobracaj', 
'die Bahn / -en ' : 'zeleznica, voz', 
'an ' : 'do, naslonjen na', 
'auf ' : 'na (stoji na necemu)', 
'hinter ' : 'iza', 
'in ' : 'u (necemu)', 
'neben ' : 'pored', 
'über ' : 'iznad', 
'unter ' : 'ispod', 
'vor ' : 'ispred', 
'zwischen ' : 'izmedju', 
'der Adler ' : 'orao', 
'PKW - Personalkraftwagen ' : 'auto', 
'LKW - Lastkraftwagen ' : 'kamion, teretno vozilo', 
'die Last ' : 'teret', 
'die Ampel ' : 'semafor', 
'in dem ' : '> im (m, n)', 
'in der ' : '> ø  (f)', 
'in den ' : '> ø  (pl)', 
'an dem ' : '> am', 
'an der ' : '> ø', 
'an den ' : '> ø', 
'N ' : 'N', 
'A ' : 'A + D', 
'D ' : 'D + L + I', 
'G ' : 'G', 
'die Wand ' : 'zid', 
'zu ' : 'do', 
'bei ' : 'kod', 
'nach ' : 'posle, nakon', 
'bei + dem ' : 'beim (m)', 
'zu + dem ' : 'zum  (m)', 
'zu + der ' : 'zur (f)', 
'die Durchsage / -n ' : 'najava (zvucna)', 
'die Abfahrt / ' : 'polazak', 
'der Abflug / -˚˚e ' : 'polazak (avionom)', 
'das Gleis ' : 'peron, sine', 
'die Ankunft ' : 'dolazak', 
'der Ausgang / -˚˚e ' : 'izlaz', 
'der Eingang / -˚˚e ' : 'ulaz', 
'einsteigen ' : 'ulazak', 
'aussteigen ' : 'izlaziti', 
'steigen ' : 'podizati, rasti, penjati se', 
'umsteigen ' : 'presedanje', 
'pünktlich ' : 'tacno na vreme', 
'der Kunde ' : 'musterija', 
'kaputt ' : 'nije u funkciji', 
'reparieren ' : 'popravka', 
'passen ' : 'odgovarati', 
'aufsetzen ' : 'staviti', 
'singen ' : 'pevati', 
'wichtig ' : 'bitno', 
'halten ' : 'drzati', 
'behalten ' : 'zadrzati', 
'zunächst ' : 'na pocetku, prvobitno', 
'das Lied ' : 'pesma', 
'bei (Zeit) ' : 'tokom, za vreme', 
'vor (Zeit) ' : 'pre', 
'bei (Zeit) ' : 'za', 
'nach (Zeit) ' : 'posle', 
'Imbiss ' : 'kios brze hrane', 
'hinauf ' : 'penjati se (obicno uz stepenice)', 
'der Strich ' : 'crta (linija)', 
'Stadtrundfahrt ' : 'obilazak grada (obucno autobusom - fahr)', 
'Ab ' : 'od (vremenska odrednica)', 
'Bis ' : 'do (vremenska odrednica)', 
'von ' : 'od (vremenska odrednica)', 
'Ab wann? ' : 'od kada?', 
'die Aufgabe ' : 'zadatak, misija', 
'schicken ' : 'poslati', 
'höflich ' : 'uctivo, kulturno', 
'buchen ' : 'rezervisati, bukirati', 
'klingen ' : 'zvucati', 
'der Fahrradständer ' : 'stalak za bicikle', 
'die Kreuzung ' : 'raskrsnica', 
'nicken ' : 'klimati glavom', 
'der Verkehrsschild ' : 'saobracajni znak', 
'die Leiche ' : 'les', 
'leihen ' : 'iznajmiti (eng. borrow)', 
'der Verleih ' : 'firma za iznajmljivanje necega', 
'überall ' : 'svuda, svugde (prostorno)', 
'anschließen ' : 'prikljuciti, staviti', 
'schließen ' : 'zatvorit', 
'können ' : 'moci', 
'werden ' : 'postati', 
'das Kleid ' : 'haljina', 
'die Kleider ' : 'odeca', 
'schnell ' : 'brzo', 
'schwer ' : 'tesko (tezina)', 
'leicht ' : 'lako, jednostvno', 
'schwierig ' : 'komplikovano', 
'stehen ' : 'stajati, pristajati', 
'gleich ' : 'isto', 
'anders ' : 'drugacije', 
'dauern ' : 'trajati', 
'einfallen ' : 'imati ideju, dosetiti se necega', 
'der Mantel ' : 'mantil', 
'gehören ' : 'pripadati', 
'ein notfall ' : 'hitan slucaj, nezgoda', 
'günstig ' : 'povoljno', 
'der Rock ' : 'suknja', 
'gefallen ' : 'svidjati se (to please)', 
'gehören ' : 'pripadati', 
'der | dieser   < ' : 'Welcher?', 
'das | dieses   < ' : 'Welches?', 
'die | diese    < ' : 'Welche?', 
'die | diese    < ' : 'Welche?', 
'Fundbüro ' : 'mesto za izgubljene stvari', 
'der Schirm ' : 'kisobran', 
'das Zeug ' : 'stvar (eng. stuff)', 
'an ziehen ' : 'obuci, obuti', 
'suchen ' : 'traziti', 
'Untergeschoss ' : 'nivo/sprat (-1)', 
'Erdgeschoss ' : 'nivo/sprat (0)', 
'der Rock ' : 'suknja', 
'feiern ' : 'proslaviti', 
'aufpassen ' : 'obracati paznju', 
'der See / -n ' : 'jezero', 
'feiern = > die Feier ' : 'das Fest', 
'die Feier ' : 'mala festa', 
'das Fest ' : 'velika festa', 
'herumfahren ' : 'voziti bez cilja', 
'das Boot / -e ' : 'plovilo, camac', 
'liegen ' : 'lezati', 
'der Boden ' : 'pod', 
'gratulieren ' : 'cestitati', 
'vergessen ' : 'zaboraviti', 
'der Rahmen ' : 'ram', 
'die Ahnung ' : 'pozivitna sumnja', 
'Keine Ahnung ' : 'nemam pojma', 
'einladen ' : 'pozvati', 
'überraschen ' : 'iznenaditi', 
'das Geschenk ' : 'poklon', 
'das Gift ' : 'otrov', 
'der Wagen ' : 'kola', 
'Mist ' : 'dodjavola (eng. Damn)', 
'eilig haben ' : 'biti u zurbi', 
'die Eile ' : 'zurba', 
'denn ' : 'jer', 
'ausgehen ' : 'izaci', 
'der Bekannte ' : 'poznanik', 
'die Kirche ' : 'crkva', 
'die Prüfung ' : 'ispit', 
'das Ding ' : 'stvar (generalno)', 
'zurzeit ' : 'sada', 
'sich kümmern um +A ' : 'startai se, brinuti o... nekome, necemu', 
'Schade ' : 'steta', 
'ohne ' : 'bez', 
'fast ' : 'uskoro (kolicina)', 
'bald ' : 'uskoro (vreme)', 
'laden ' : '(eng. load)', 
'werden ' : 'postati', 
'zumachen ' : 'zatvoriti', 
'anmachen ' : 'ukljuciti, muvati (slang)', 
'aufmachen ' : 'otvoriti', 
'ausmachen ' : 'iskljuciti', 
'der Arbeiter / - ' : 'radnik', 
'die Stelle / -n ' : 'pozicija', 
'das Jahr / -e ' : 'godina', 
'die Woche / -n ' : 'nedelja', 
'der Berg / -e ' : 'brdo, planina', 
'das Land / ' : 'zemlja', 
'die Idee / -n ' : 'ideja', 
'die Stunde / -n ' : 'jedan sat', 
'der Kindergarten / - ˚˚ ' : 'vrtic', 
'das Abendessen / - ' : 'vecera', 
'das Fenster / - ' : 'prozor', 
'der Kalendar / - ' : 'kalendar', 
'das Auto / -s ' : 'auto', 
'das Foto / -s ' : 'fotografija', 
'das Ticket / -s ' : 'karta', 
'treffen (hat getroffen) ' : 'sresti', 
'eilig ' : 'hitno', 
'wunderbar ' : 'predivno', 
'reisen (ist gereist) ' : 'putovati', 
'helfen ' : 'pomoci', 
'hinfahren ' : 'voziti pravo', 
'das Au-pair ' : 'bebisiterka', 
'die Behörde / -n ' : 'drzavni cinovnik (administracija)', 
'das Ding / -e ' : 'stvar', 
'das Zeug ' : 'stvar', 
'der Gegenstand ' : 'stvar', 
'die Sache ' : 'stvar (abstraktno)', 
'du Arme (f) ' : 'mukice, jadnice (u smislu sazaljenja)', 
'du Armer (m) ' : 'mukice, jadniche (u smislu sazaljenja)', 
'das Rad / -˚˚er ' : 'tocak', 
'versuchen ' : 'probati, pokusati', 
'der Sitz / -e ' : 'sediste', 
'verlieren (+A) ' : 'izgubiti', 
'nehmen +A ' : 'uzeti', 
'schwierig ' : 'tesko (za rad)', 
'schwer ' : 'tesko (tezina)', 
'trennen ' : '> getrennt', 
'trennen (hat getrennt) ' : 'odvojiti, razdvojiti', 
'getrennt (pII) ' : 'odvojeno', 
'einschlafen ' : 'zaspati', 
'rechthaben ' : 'biti u pravu, imaiti pravo', 
'schrecklich ' : 'strasno, jezivo', 
'der Schreck ' : 'uplasiti, shok (eng. fear, shock)', 
'verpassen (hat verpasst) ' : 'propustiti (prilika, prevozno sredstvo)', 
'eigentlich ' : 'zapravo', 
'denn ' : 'jer (veznik, nezavisna recenica)', 
'weil ' : 'jer, zato sto, zbog (veznik, zavisna recenica)', 
'einzige ' : 'jedino', 
'einzig- ' : 'jedinstveni, jedan, jedini', 
'bald ' : 'uskoro (vreme)', 
'aufwachen ' : 'probuditi se', 
'aufstehen ' : '> aufgestanden', 
'aufwachen ' : '> aufgewachen', 
'anrufen ' : '> angerufen', 
'einkaufen ' : '> eingekauft', 
'peinlich ' : 'blamaza', 
'nämlich ' : 'naime, zapravo', 
'steigen ' : 'rasti, penjati se, uci u neko vozilo', 
'zurückfahren ' : 'vratiti se', 
'ankommen ' : 'stici (negde, na cilj)', 
'schließlich ' : 'konacno, na kraju, zakljucno', 
'verpassen ' : '> verpasst', 
'bekommen ' : '> bekommen', 
'gehören ' : '> gehört', 
'erleben ' : '> erlebt', 
'passieren ' : '> passiert', 
'erleben ' : 'doziveti', 
'besichtigen ' : 'razgledati', 
'der Zufall ' : 'slucajnost', 
'sich melden ' : 'javi se', 
'Verwandtschaft ' : 'rodbina', 
'der Schwager ' : 'zet', 
'die Schwägerin ' : 'zetova sestra', 
'der Erdgeschoss ' : 'prizemlje', 
'die Dachwohnung / -en ' : 'potkrovlje', 
'die allein erziehende Mutter ' : 'samohrana majka', 
'der Müll ' : 'otpad', 
'die Wand / -˚˚e ' : 'zid (unutra)', 
'die Mauer ' : 'zid (spolja)', 
'halten +A ' : 'drzati', 
'die Müll ' : '> die Mülltonne', 
'die Müll ' : 'otpad', 
'die Mülltonne ' : 'kanta za otpad', 
'der Hof ' : 'dvoriste', 
'die Menge ' : 'kolicina', 
'trennen ' : 'razdvojiti', 
'getrennt ' : 'odvojeno', 
'anders ' : 'drugacije', 
'Recht haben ' : 'biti u pravu', 
'klingen ' : 'zvucati', 
'sorgen (hat gesorgt) ' : 'starati se', 
'werfen ' : 'baciti (grudva, kamen ... u bukvalnom smislu)', 
'wegwerfen ' : 'baciti (u smislu... otarasiti se)', 
'wecken (hat gewecht) ' : 'probuditi se, uzbuditi se', 
'das Amt ' : 'ministarstvo, sluzba', 
'verbessern (hat verbessert) ' : 'popraviti', 
'der Keller / - ' : 'podrum', 
'zufrieden ' : 'zadovoljan', 
'Die beiden ' : 'dvoje (eng. both)', 
'der Haken ' : 'kuka', 
'der Kasten ' : 'kutija', 
'der Briefkasten ' : 'postansko sanduce', 
'die Tafel ' : 'tabla', 
'die Nichte ' : 'bratanica/sestricina', 
'der Neffe ' : 'bratanac/sestric', 
'verloren ' : 'izgubiti', 
'schwanger ' : 'biti trudan', 
'rein ' : 'unutra (prefiks kretanja)', 
'raus ' : 'napolje (prefiks kretanja)', 
'rauf ' : 'gore (prefiks kretanja)', 
'runter ' : 'dole (prefiks kretanja)', 
'rüber ' : 'preko (prefiks kretanja)', 
'runterbringen ' : 'saneti dole', 
'raufbringen ' : 'doneti gore', 
'rauskommen (ist rausgekommen) ' : 'izaci napolje', 
'reinkommen (ist rausgekommen) ' : 'uci unutra', 
'raufkommen (ist raufgekommen) ' : 'ici gore', 
'das Amt / -˚˚er ' : 'ministarstvo, sluzba', 
'der Anruf / -e ' : 'poziv (telefonski)', 
'Tratsch ' : 'trach', 
'das Mietshaus ' : 'zgrada', 
'sonnig ' : 'suncano', 
'der Streit ' : 'svadja', 
'keine Ahnung ' : 'nemam pojma', 
'Fürst ' : 'knez', 
'einfallen +D ' : 'dosetiti se', 
'der Kinderwagen ' : 'decja kolica', 
'die Kiste / -n ' : 'kutija (obicno drvena)', 
'abstellen (hat abgestellt) ' : 'ostaviti (nesto)', 
'ausleihen (hat ausgeliehen) ' : 'pozajmiti', 
'der Aufzug ' : 'lift', 
'der Hausmeister / - ' : 'domar, kucepazitelj', 
'unterwegs ' : 'usput, na putu', 
'beruflich ' : 'poslovno (eng. bussiness)', 
'hoffentlich ' : 'nadam se (eng. hopefully)', 
'sei mir nich böse ' : 'nemoj se ljutiti na mene', 
'schimpfen ' : 'grditi, psovati', 
'die Mitteilung / -en ' : 'saopstenje', 
'danach ' : 'posle', 
'Wohngemeinschaft ' : 'cimeri, stambena zajednica', 
'übrigens ' : 'usput (eng. btw)', 
'gegen ' : 'oko (vremenski)', 
'gießen (hat gegossen) ' : 'zalivati', 
'die Pflanze / -n ' : 'biljka', 
'der Strom ' : 'struja', 
'verbraucht ' : 'potrositi', 
'verbrauchen (hat verbraucht) ' : 'trositi', 
'wahnsinnig ' : 'mnogo, bolesno mnogo', 
'ärgerlich ' : 'frustrirajuce (eng. irritating)', 
'furchtbar ' : 'strasno', 
'furchtbar eilig ' : 'strasno zurim', 
'es eilig haben ' : 'zurim', 
'erwarten (hat erwartet) ' : 'ocekivati', 
'Bescheid sagen ' : 'obavestiti', 
'der Schmutz ' : 'prljavstina', 
'sauber ' : 'cisto', 
'schmutzig ' : 'prljavo', 
'der Zettel / - ' : 'cedulja', 
'der Boden / -˚˚e ' : 'pod', 
'die Decke / -n ' : 'cebe, deka', 
'das Regal / -e ' : 'regal', 
'der Teppich / -e ' : 'tepih', 
'die Toilete / -n ' : 'toalet', 
'hängen (hat/ist gehangen, hat gehängt) ' : 'okaciti, obesiti', 
'hoffen (hat gehofft) ' : 'nadati se', 
'legen (hat/ist gelegen) ' : 'polegnuti', 
'stellen (hat gestellt) ' : 'staviti', 
'fröhlich ' : 'veseo', 
'sauer ' : 'kiseo (raspolozenje)', 
'traurig ' : 'tuzan', 
'So ein Pech! ' : 'kakva steta', 
'So ein Zufall! ' : 'kakva slucajnost', 
'einziehen (ist eingezogen) ' : 'pokupiti, prisvojiti', 
'erziehen (hat erzogen) ' : 'odgajati, trenirati (nekoga)', 
'auf einmal ' : 'najednom', 
'erst einmal ' : 'za pocetak, prvobitno', 
'schon einmal ' : 'vec jednom', 
'wenigstens ' : 'minimalno, bar malo', 
'der Nachbar / -n ' : 'komsija', 
'einrichten ' : 'organizovati, spremiti, uspostaviti', 
'nachsehen ' : 'proveriti', 
'sorgen ' : 'brinuti se, pobrinuti se', 
'sonst ' : 'inace', 
'allgemein ' : 'inace, generalno', 
'mundfaul ' : 'onaj koji slabo prica', 
'der Durchschnitt ' : 'prosek', 
'durchschnittlich ' : 'prosecno', 
'die Gewohnheit ' : 'obicno, navika', 
'die Nuss ' : 'orah, kostunjavo voce', 
'fehlen ' : 'nedostajati (eng. to miss, to lack)', 
'wach (sein) ' : 'budan (biti)', 
'aufwachen ' : 'probuditi se', 
'aufwecken +A ' : 'probuditi se', 
'schläfrig ' : 'pospan', 
'munter ' : 'oran, cio', 
'weich ' : 'mekano', 
'hart ' : 'tvrdo', 
'ausschlafen ' : 'naspavati se', 
'die Störung ' : 'smetnja', 
'(sich) entscheiden ' : 'odluciti (se)', 
'frisch ' : 'sveze', 
'dazu ' : 'dodatno (nedovoljno)', 
'stark ' : 'jako', 
'schwach ' : 'slabo', 
'aussagen ' : 'tvrditi, otkriti', 
'die Tasse / -n ' : 'solja', 
'der Kakau ' : 'kakao', 
'der Fan ' : 'fan', 
'der Bettelmann ' : 'prosjak, siromah', 
'handeln ' : '> die Handlung', 
'die Handlung ' : 'tema', 
'verschieden ' : 'razlicito', 
'anders ' : 'drugacije', 
'ähnlich ' : 'slicno', 
'gleich ' : 'isto', 
'identisch ' : 'identicno', 
'Ehrlich ' : 'iskreno', 
'allerdings ' : 'niposto, nikako, zapravo', 
'Gott sei Dank ' : 'bogu hvala', 
'die Menge ' : 'kolicina', 
'besonders ' : 'posebno', 
'tagelang ' : 'danima', 
'stundenlang ' : 'satima', 
'jahrelang ' : 'godinama', 
'wochenlang ' : 'nedeljama', 
'reden (hat geredet) ' : 'pricati', 
'der Gott ' : 'bog', 
'nachgefragt < ' : 'nachfragen', 
'nachfragen ' : 'propitati', 
'drinnen ' : 'unutra', 
'draußen ' : 'napolju', 
'sogar ' : 'cak', 
'der Sekt ' : 'penusavo vino', 
'herzhaft ' : 'prijatno (srcu)', 
'fast ' : 'skoro (eg. 99%)', 
'bald ' : 'uskoro (eg. 19h55)', 
'immer ' : 'uvek', 
'meistens ' : 'uglavnom', 
'oft ' : 'cesto', 
'manschman ' : 'ponekat', 
'selten ' : 'retko', 
'nie ' : 'nikada', 
'mittags ' : 'u podne', 
'morgens ' : 'ujutro', 
'abends ' : 'uvece', 
'werktags ' : 'radni dani', 
'wochentags ' : 'dani u nedelji', 
'das Vollkornbrot ' : 'hleb sa semenkama', 
'Rinderbraten ' : 'telece pecenje', 
'braten (hat gebraten) ' : 'peci ', 
'der Kürbisc ' : 'bundeva', 
'der Essig ' : 'sirce', 
'außerdem ' : 'osim toga', 
'die Bude ' : 'mali prostor, gajba', 
'Mahlzeit ' : 'obrok', 
'holen ' : 'otici uzeti nesto i doneti (ceo postpupak)', 
'dagegen ' : 'naprotiv, sa druge strane', 
'nirgends ' : 'nigde', 
'genauso ' : 'podjednako, kao, slicno kao', 
'unterschiedliche ' : 'drugacije', 
'die Art ' : 'vrsta', 
'beschäftigen ' : 'baviti se, uzimati paznju', 
'widmen ' : 'postetiti', 
'die Widmung ' : 'posveta', 
'schneiden (hat geschnitten) ' : 'seci', 
'darüber ' : 'preko toga', 
'das Gericht ' : 'obrok', 
'geheimen ' : 'tajno, sakrivajuci se', 
'geheim ' : 'tajna', 
'das Rezept ' : 'recept', 
'herstellen ' : 'proizvoditi', 
'himmlisch ' : 'nebesko, rajsko', 
'ehemaligen ' : 'bivsi', 
'der Regierungschef ' : 'premier', 
'die Einladung ' : 'pozivnica', 
'das Benehmen ' : 'bonton', 
'die Regel ' : 'pravilo', 
'dauren ' : 'trajati', 
'die Dauer ' : 'traje', 
'ausmachen ' : 'dogovoriti se, iskljuciti', 
'die Verspätung ' : 'kasnjenje', 
'die Nachspeise ' : 'dezert', 
'die Weile ' : 'neodredjeno vreme (dugo ili kratko)', 
'der Gastgebern ' : 'domacin', 
'satt ' : 'sit', 
'übrig ' : 'visak', 
'nötig ' : 'neophodno, potrebno', 
'das Gebäck ' : 'pecivo', 
'der Teig ' : 'testo', 
'die Sorte ' : 'sorta', 
'schicken ' : 'poslati (fizicki)', 
'senden ' : 'poslati (elektronski)', 
'die Stange / -n ' : 'stangla', 
'prima ' : 'super', 
'die Backstube ' : 'soba sa pecnicom', 
'sparen (hat gespart) ' : 'stedeti, sparati', 
'probieren ' : 'pokusati, okusiti', 
'fett ' : 'mast', 
'frisch ' : 'sveze', 
'salzig ' : 'slano', 
'sauer ' : 'kiselo', 
'scharf ' : 'ljuto, ostro', 
'süß ' : 'slatko', 
'die Bohne / -n ' : 'pasulj', 
'der Braten / - ' : 'peceno', 
'die Gabel / -n ' : 'viljuska', 
'der Becher / - ' : 'solja', 
'die Pfanne / -n ' : 'tiganj', 
'die Schüssel / -n ' : 'cinija', 
'die Tasse / -n ' : 'solja', 
'der Topf / -˚˚e ' : 'serpa', 
'duschen (hat geduscht) ' : 'tusirati se', 
'lassen (hat gelasse) ' : 'pustiti, dozvoliti', 
'besetzt ' : 'zauseti', 
'Welch ' : 'stranac (staro nemacki)', 
'Ostsee ' : 'Balticko more', 
'Ratschlag ' : 'savet, predlog', 
'beachten ' : 'obratiti paznju na nesto', 
'achten ' : 'pazi na ...', 
'sachliche ' : 'strucno', 
'beendet ' : 'zavrsiti, okoncati', 
'beantworten ' : 'odgovoriti', 
'der Rat ' : 'savet', 
'überstunden ' : 'prekovremeno vreme', 
'übertreiben ' : 'preterivati', 
'Wenn ' : 'ako', 
'Dann ' : 'jer', 
'die Teilzeit ' : 'pola vremena (radnog)', 
'betrunken ' : 'pijan', 
'da vorn ' : 'tamo napred', 
'der Arbeitsplatz ' : 'radno mesto', 
'ausrichten +A ' : 'informisati <A>', 
'außer ' : 'van(i)', 
'die Durhwahl ' : 'pozivni broj', 
'noch nicht ' : 'jos ne', 
'insgesamt ' : 'sve ukupno', 
'die Spitze ' : 'vrh', 
'zumindest ' : 'minimalno', 
'betreffen ' : 'ticati se', 
'Angestellten ' : 'zaposleni', 
'das Büro / -s ' : 'kancelarija', 
'der Empfang / -˚˚e ' : 'prijem', 
'der Eport / -e ' : 'izvoz', 
'die Fabrik / -en ' : 'fabrika', 
'die Maschine / -n ' : 'masina', 
'die Mehrwertsteuer ' : 'PDV', 
'das Produkt / -e ' : 'proizvod', 
'die Quittung / -en ' : 'racun (eng. receipt)', 
'die Überstunde / -n ' : 'prekovremeno (eng. overtime)', 
'außer Haus ' : 'van kuce', 
'das Gebäck ' : 'kolacici', 
'der Hammer / -˚˚ ' : 'cekic', 
'das Handwerk ' : 'rucni rad', 
'der Handwerker ' : 'zanatlija (eng. craftsman)', 
'die Nagel ' : 'ekser', 
'der Meister ' : 'sampion, majstor, ekspert', 
'das Holz / -˚˚er ' : 'drvo', 
'der Vogel / -˚˚ ' : 'ptica', 
'der Wald / -˚˚er ' : 'suma', 
'die Meinung / -en ' : 'misljenje', 
'der Rat ' : 'savet, pacov', 
'das Symbol / -e ' : 'simbol', 
'der Teil / -e ' : 'deo, sekcija, poglavlje', 
'der Typ / -en ' : 'tip', 
'anbieten (hat angeboten) ' : 'ponuditi, obezbediti', 
'abschließen (hat abgeschlossen) ' : 'zakljucati, zavrsiti', 
'ausgeben (hat ausgegeben) ' : 'potrositi, rasprsiti, pustiti', 
'ausschalten (hat ausgeschalten) ' : 'onesposobiti, ugasiti, iskljuciti', 
'entscheiden (hat entschieden) ' : 'odluciti', 
'erkennen (hat erkannt) ' : 'prepoznati, detektovati', 
'merken (hat gemerkt) ' : 'zapaziti, zapisati, skrenuti paznju na netso (zameriti)', 
'spülen (hat gespült) ' : 'prati, pustiti vodu', 
'stören (hat gestört) ' : 'uznemiravati, remetiti, mesati se', 
'wählen (hat gewählt) ' : 'birati (telefonski broj)', 
'übersetzen (hat übersetzt) ' : 'prevoditi', 
'gleichfalls ' : 'takodje', 
}; 
