/*
 * Resources
 */


const words = { 
'machen ' : 'ciniti, raditi', 
'arbeiten ' : 'raditi', 
'heißen ' : 'zvati se', 
'essen ' : 'jesti', 
'lessen ' : 'citati', 
'fahren ' : 'voziti', 
'laufen ' : 'trcati, setati', 
'sein ' : 'biti', 
'sagen ' : 'reci, kazati', 
'ordnen ' : 'rasporediti', 
'(Herzlich) Willkommen ' : '(Srdacno) Dobrodosli', 
'bitte ' : 'molim', 
'Freut mich ' : 'drago mi je', 
'die Stadt ' : 'grad', 
'die Hauptstadt ' : 'glavni grad', 
'der Unterschit ' : 'razlika', 
'der Schüler ' : 'ucitelj', 
'der Lerner ' : 'ucenik', 
'der Stadtführer ' : 'gradski vodic', 
'der Spaß ' : 'zabava', 
'die Straße ' : 'ulica', 
'das Gegenteil ' : 'suprotnost', 
'lesen ' : 'citati', 
'schreiben ' : 'pisati', 
'der Gegenstand ' : 'predmet (fizicki)', 
'Wer ' : 'ko?', 
'Was ' : 'sta?', 
'Wo ' : 'gde?', 
'Woher ' : 'odakle?', 
'Wohin ' : 'kuda?', 
'Wann ' : 'kada?', 
'Wie ' : 'kako?', 
'drehen ' : 'listati', 
'ergänzen ' : 'dopuniti', 
'Satzzeichen ' : '? , . ; :', 
'der Wasserhahn ' : 'cesma', 
'lernen ' : 'uciti', 
'lehren ' : 'poducavati', 
'überspringen ' : 'preskociti', 
'springen ' : 'skociti', 
'das Gespäch ' : 'razgovor', 
'unbekannte ' : 'nepoznato', 
'Buchstaben ' : 'slovo', 
'bedeuten ' : 'znaciti', 
'Entschuldigung ' : 'izvinite', 
'buchstabieren ' : 'spelovati', 
'da ' : 'tu (mesto)', 
'Vorname ' : 'Name', 
'Familienname ' : 'Nachname', 
'Land ' : 'zemlja (tlo)', 
'die Folge ' : 'epizoda', 
'das Bild ' : 'slika', 
'bereit ' : 'spreman', 
'meinen ' : 'misliti (stav)', 
'hübsch ' : 'lepa (najcesce za zene)', 
'schön ' : 'hübsch', 
'wohnen ' : 'stanovati', 
'leben ' : 'ziveti', 
'der Tee ' : 'caj', 
'der Kaffee ' : 'kafa', 
'der Moment ' : 'trenutak', 
'die Eltern ' : 'roditelji', 
'die Mutter ' : 'majka', 
'der Vater ' : 'otac', 
'die Großmutter ' : 'baka', 
'die Schwester ' : 'sestra', 
'der Bruder ' : 'brat', 
'die Geschwister ' : 'eng. siblings (brat i sestra, brat i brat, sestra i sestra)', 
'groß ' : 'veliko', 
'klein ' : 'malo', 
'die Übung ' : 'vezba', 
'sagen ' : 'reci, kazati', 
'hier ' : 'ovde', 
'da ' : 'tu', 
'dort ' : 'tamo', 
'Ihnen ' : 'Vama', 
'Dir ' : 'tebi', 
'müde ' : 'umoran', 
'erholten ' : 'odmoran', 
'öffnen ' : 'otvoriti', 
'offen ' : 'otvoren', 
'der Abschnitt ' : 'sekcija, odsek', 
'das Kind ' : 'dete', 
'der Lehrer ' : 'ucitelj', 
'der Lerner ' : 'ucenik', 
'der Sohn / die Söhne ' : 'sin / sinovi', 
'die Tochter ' : 'kcerka', 
'das Rätsel ' : 'zagonetka', 
'die Zahlen ' : 'brojevi', 
'die Zahl ' : 'broj', 
'zahlen ' : 'platiti', 
'die Nummer ' : 'broj', 
'bezahlen ' : 'platiti (odmah)', 
'die Lösung ' : 'resenje', 
'Liegen ' : 'lezati', 
'verheiratet ' : 'vencan / a', 
'geschieden ' : 'razveden / a', 
'haben ' : 'imati', 
'alt ' : 'staro', 
'jung ' : 'mlado', 
'die Heimatland ' : 'domovina, zemlja porekla', 
'der Ort ' : 'mesto', 
'der Wohnort ' : 'prebivaliste', 
'Familienstand ' : 'bracno stanje', 
'ledig ' : 'neozenjen, posle 18g (eng. single)', 
'verwitwet ' : 'udovac / ica', 
'die Witwe ' : 'udovica', 
'der Witwer ' : 'udovac', 
'der Herr ' : 'gospodin', 
'die Frau ' : 'gospodja', 
'der Titel ' : 'naslov', 
'Sich vorstellen ' : 'predstaviti se', 
'viele ' : 'mnogo', 
'das Baby ' : 'beba', 
'der Freund ' : 'prijatelj', 
'die Freundin ' : 'prijateljica', 
'leider ' : 'nazalost', 
'es tut mir leid ' : 'zao mi je', 
'König ' : 'kralj', 
'lang ' : 'dugo', 
'kurz ' : 'kratko', 
'gegenteil ' : 'suprotnost', 
'die Seite ' : 'strana', 
'passen ' : 'biti taman', 
'zeigen ' : 'pokazati', 
'an kreuzen ' : 'obeleziti, markirati', 
'auf füllen ' : 'popuniti', 
'der Mensch / -en (pl) ' : 'covek, ljudi (pl)', 
'der Apfel ' : 'jabuka', 
'die Erde ' : 'zemlja (zemljiste, materijal)', 
'der Markt ' : 'pijaca', 
'folgen ' : 'pratiti', 
'die Folge ' : 'epizoda', 
'brauchen ' : 'potreban ( eng. need )', 
'das Problem ' : 'problem', 
'wie viel? ' : 'koliko?', 
'das Kilo ' : 'kilo', 
'das Obst ' : 'voce', 
'juner Mann ' : 'mladic', 
'sonst noch etwas ' : 'inace jos nesto', 
'sonst ' : 'inace', 
'noch ' : 'jos', 
'etwas ' : 'nesto', 
'vielleicht ' : 'mozda', 
'kosten ' : 'kostati', 
'die Kosten ' : 'troskovi', 
'gern(e) ' : 'rado', 
'das Wort / - en ' : 'rec', 
'die Wörten ' : 'reci', 
'das Lebensmittel ' : 'namirnice', 
'Nennen ' : 'imenovati', 
'das Brötchen ' : 'kifla, zemicka, pecivo', 
'bisschen ' : 'ugriz', 
'der Biss ' : 'ujed, ugriz, zalogaj', 
'schauen ' : 'gledati', 
'sehen ' : 'videti', 
'der Kuchen ' : 'kolac', 
'die Tomate ' : 'paradajz', 
'der Ort / -e (pl) ' : 'mesto', 
'der Korb / -e (pl) ' : 'korpa', 
'im ' : 'unutra', 
'der Fisch / -e (pl) ' : 'riba', 
'die Traube / -en (pl) ' : 'grozdje', 
'der Saft / -e (pl) ' : 'sok', 
'die Säfte ' : 'sokovi', 
'drehen ' : 'okrenuti', 
'der Zettel ' : 'cedulja', 
'alles ' : 'sve', 
'nichts ' : 'nista', 
'der Sahne ' : 'slag', 
'die Brille ' : 'naocare', 
'die Birne ' : 'kruska', 
'vergleichen ' : 'porediti', 
'gleich ' : 'isto (eng. same)', 
'das Beispiel ' : 'primer', 
'die Anmeldung ' : 'prijava', 
'das Gewicht ' : 'masa', 
'die Maß ' : 'mera', 
'die Maßeinheiten ' : 'merna jedinica', 
'die Einheit ' : 'jedinica (u bilo kom obliku)', 
'die Abteilung ' : 'odeljak, odsek', 
'das Angebote ' : 'ponuda', 
'sonder ' : 'specijalna, posebna', 
'oben ' : 'gore', 
'unter ' : 'dole', 
'mitte ' : 'u sredini', 
'links ' : 'levo', 
'rechts ' : 'desno', 
'die Null ' : 'nula', 
'komma ' : 'zarez', 
'das Öl ' : 'ulje', 
'die Flasche ' : 'boca, flasa', 
'die Packung ' : 'pakovanje', 
'das Rind ' : 'govece', 
'die Kuh ' : 'krava', 
'der Bulle / der Stier ' : 'vo, bik', 
'die Rindfleich ' : 'govedina', 
'die Dose ' : 'konzerva', 
'die Dosis ' : 'mera (leka)', 
'der Becher ' : 'mala posuda, iskljucivo od plastike (casa za jogurt, ...)', 
'essen ' : 'jesti', 
'das Esse ' : 'jelo', 
'lieblings ' : 'omiljeni', 
'der Liebling ' : 'miljenik', 
'der Film ' : 'film', 
'die Soße ' : 'sos', 
'das Hähnchen ' : 'piletina', 
'der Durst ' : 'zedan', 
'der Hunger ' : 'gladan', 
'mögen ' : 'svidjati, gotiviti (eng. like)', 
'lieben ' : 'voleti (strastveno)', 
'schmecken ' : 'osecati ukus', 
'der Geschmack ' : 'ukus (generano)', 
'Vorsicht! ' : 'pazi', 
'die Vorsicht ' : 'paznja, obazrivost', 
'vorsichtig ' : 'obazriv', 
'das Zimmer ' : 'prostorija, soba', 
'Wohnzimmer ' : 'dnevna soba', 
'der Stock ' : 'sprat', 
'die Möbel (pl) ' : 'namestaj', 
'das Möbelstück ' : 'komad namestaja', 
'der Schritt ' : 'korak', 
'die Schritte ' : 'koracati', 
'kennen ' : 'poznavati ( mesto ili vestina )', 
'weiter ' : 'dalje', 
'teuer ' : 'skupo', 
'billig ' : 'jeftino', 
'der Einfall ' : 'dosetka, ideja', 
'die Idee ' : 'ideja (internacionalno)', 
'machen ' : 'ciniti, raditi', 
'noch ' : 'jos', 
'unmöglich ' : 'nemoguce', 
'gerfallen ' : 'dopadati se (gotiviti)', 
'finden ' : 'naci (gotiviti)', 
'gut ' : 'dobro', 
'schlect ' : 'lose (kvalitet)', 
'schlimm ' : 'lose (situacija)', 
'böse    ' : 'zlo, lose (moralno, eticki)', 
'verrückt ' : 'iscasen, poremecen', 
'seltsam ' : 'neobicno, cudno', 
'höflich ' : 'ljubazan, uctiv', 
'freundlich ' : 'prijatan', 
'der Flur ' : 'hodnik', 
'laut ' : 'glasno', 
'leise ' : 'tiho', 
'wirklich ' : 'stvarno, zaista', 
'das Haus ' : 'kuca', 
'breit ' : 'siroko', 
'schmal ' : 'usko', 
'schön ' : 'lepo', 
'hässlich ' : 'ruzno', 
'hell ' : 'svetlo', 
'dunkel ' : 'tamno', 
'zwichen ' : 'izmedju, medju', 
'vergleichen ' : 'uporediti', 
'das Ratespiel ' : 'igra pogadjanja', 
'aber ' : 'vrlo, veoma, bas, ali', 
'die Dusche ' : 'tus', 
'das Bett ' : 'krevet', 
'das Wasschbecken ' : 'lavabo', 
'der Schrank ' : 'ormar', 
'der Kühlschrank ' : 'frizider', 
'der Herd ' : 'sporet, rerna', 
'die Badewanne ' : 'kada', 
'der Fernseher ' : 'televizor', 
'die Spühle ' : 'sudopera', 
'das Gerät ' : 'uredjaj, stroj, masina', 
'grün ' : 'zelena', 
'gelb ' : 'zuta', 
'grau ' : 'siva', 
'anzeigen ' : 'oglasi', 
'der Preis ' : 'cena, nagrada', 
'preiswert ' : 'jeftin', 
'mieten ' : 'onaj koji zakupljuje (stanar)', 
'vermieten ' : 'onaj koji daje u najam (vlasnik)', 
'die Miete ' : 'izdavati', 
'das Praktikum ' : 'praksa', 
'die Praxis ' : 'ordinacija', 
'möbliert ' : 'namesten', 
'die Zeit ' : 'vreme (u kontekstu sata)', 
'das Wetter ' : 'vreme (u kontekstu vremenske prognoze)', 
'voll ' : 'puno', 
'leer ' : 'prazno', 
'der Raum ' : 'prostor', 
'die Lage ' : 'stanje, leziste, situirano', 
'die Woche ' : 'sedmica', 
'ruhig ' : 'mirno', 
'die Ruhe ' : 'mir (spokoj)', 
'neben ' : 'pored (uopsteno)', 
'Nebenkosten ' : 'sporedni troskovi', 
'sitzt ' : 'sedeti', 
'jetzt ' : 'sada', 
'sofort ' : 'odmah', 
'dringend ' : 'hitno, vazno', 
'warm ' : 'toplo', 
'kalt ' : 'hladno', 
'die Ferien ' : 'raspust', 
'der Urlaub ' : 'odmor', 
'der Stern ' : 'zvezda', 
'das Zeichen ' : 'znak', 
'glauben ' : 'verovati', 
'antworten ' : 'odgovoriti (usmeno, pismeno,...)', 
'helfen ' : 'pomoci', 
'möchten ' : 'zeleti (eng. wish)', 
'Sternzeichen ' : 'horoskop', 
'an ' : 'na (predlog)', 
'Steinbock ' : 'jarac', 
'gemütliches ' : 'udobno', 
'vor allem ' : 'pre svega', 
'knallrotes ' : 'drecavo crvena', 
'besonders gern ' : 'posebno drago/draga', 
'Welche ' : 'koja, koji', 
'lecker ' : 'ukusno', 
'einrichten ' : 'uredjen', 
'der Knall ' : 'eksplozija', 
'der Wunsch ' : 'zelja (u bukvalnom smislu)', 
'wünschen ' : 'zeleti', 
'die Gemültichkeit ' : 'udobno', 
'das Herz ' : 'srce', 
'der Bahnhof ' : 'zeleznicka stanica', 
'der Stift ' : 'pisljka (olovka)', 
'der Shal ' : 'sal', 
'die Jacke ' : 'jakna', 
'schon ' : 'vec, bas', 
'der Tag ' : 'dan', 
'genug ' : 'dovoljno, dosta', 
'die Sprache ' : 'jezik', 
'sprechen ' : 'pricati', 
'aufstehen ' : 'ustati', 
'aufräumen ' : 'pospremiti', 
'stimmt ' : 'tako je', 
'einkaufen ' : 'kupovati', 
'kaufen ' : 'kupiti', 
'kochen ' : 'kuvati', 
'frühstücken ' : 'doruckovati', 
'das Frühstück ' : 'dorucak', 
'fernsehen ' : 'gledati televiziju', 
'der Fernseher ' : 'televizor', 
'lustig ' : 'smesno', 
'ernst ' : 'ozbiljno', 
'traurig ' : 'tuzno', 
'langweilig ' : 'dosadan', 
'doof ' : 'simpaticno glupo', 
'dumm ' : 'neutralno glupo', 
'blöd ' : 'glup (uvredljivo)', 
'nett ' : 'fino, ljubazno (eng. nice)', 
'lachen ' : 'smejati se', 
'geben ' : 'dati, postojati ... (e -> i)', 
'spät ' : 'kasno', 
'früh ' : 'rano', 
'der Zeiger ' : 'kazaljka', 
'der Vollidiot ' : 'potpuni idiot', 
'die Uhr ' : 'sat (masina, rucni sat, ... eng. watch)', 
'die Stunde ' : 'cas (60 min ... eng. hour)', 
'vorspielen ' : 'odsvirati', 
'verbinden ' : 'povezati', 
'zu spät kommen ' : 'zakasniti', 
'aufräumen ' : 'pospremiti', 
'anrufen ' : 'pozvati (telefonom)', 
'aufstehen ' : 'ustati', 
'stehen ' : 'stajati', 
'fernsehen ' : 'gledati tv', 
'drehen ' : 'okretati', 
'umdrehen ' : 'okrenuti (jednom)', 
'die Sonne ' : 'sunce', 
'der Mittag ' : 'podne', 
'der Vormittag ' : 'pre podne', 
'der Nachmittag ' : 'posle podne', 
'der Morgen ' : 'jutro, sutra', 
'heute ' : 'danas', 
'der Abend ' : 'vece', 
'die Nacht ' : 'noc', 
'am ' : '(eng. in)', 
'in der Nacht ' : 'tokom noci', 
'von ' : 'od', 
'bis ' : 'do', 
'am ' : 'dane u sedmici i/ili doba dana', 
'um ' : 'kod satnice', 
'die Schicht ' : 'smena, sloj', 
'jeden Tag ' : 'svakog dana', 
'jeden ' : 'svaki', 
'jede ' : 'savi', 
'Öffnungszeit / -en ' : 'radno vreme', 
'der Depp ' : 'debil od milosti', 
'das Joggen ' : 'dzogiranje', 
'zwei mal ' : 'dva puta', 
'mal ' : 'puta (npr. koliko puta)', 
'traiben ' : 'terati (osobu, stoku)', 
'Sport treiben ' : 'baviti se sportom', 
'fechten ' : 'macevanje', 
'auch ' : 'isto, takodje', 
'mitkommen ' : 'doci sa nekim', 
'der Wetter ' : 'vreme', 
'regnen ' : 'pada kisa', 
'der Regen ' : 'kisa', 
'scheinen ' : 'sijati, ciniti se', 
'die Lust ' : 'volja', 
'Lust haben ' : 'imati volju, biti u fazonu', 
'das Schloss ' : 'zamak, brava (mehanizam)', 
'der Schuh/ -e ' : 'obuca, cipela', 
'der Anzug/ - ˚˚ e ' : 'odeca, odelo', 
'das Geld ' : 'novac', 
'Mach nicht ' : 'nema veze', 
'schnell ' : 'brzo', 
'langsam ' : 'sporo', 
'öft ' : 'ucestalo', 
'selten ' : 'retko', 
'aufrufen ' : 'prozvati', 
'anrufen ' : 'pozvati (telefonom)', 
'weitermachten ' : 'nastaviti (dalje sa radom)', 
'der Laden ' : 'radnja', 
'das Geschäft ' : 'eng. bussiness', 
'vielleicht ' : 'mozda', 
'der Quatsch ' : 'besmislica (eng. nonesense)', 
'der Obstladen ' : 'prodavnica voca', 
'der Wind ' : 'vetar', 
'windig ' : 'vetrovito', 
'warm ' : 'toplo', 
'kalt ' : 'hladno', 
'schneien ' : 'snezi, pada sneg', 
'der Schnee ' : 'sneg', 
'bewölkt ' : 'oblacno', 
'die Wolke ' : 'oblak', 
'Norden ' : 'sever', 
'Süden  ' : 'jug', 
'Westen ' : 'zapad', 
'Osten  ' : 'istok', 
'das Kraut ' : 'biljka', 
'die Jahreszeiten ' : 'godisnja doba', 
'der Satz / -˚˚e ' : 'recenica', 
'gucken ' : 'gledaj, baci pogled', 
'nehmen ' : 'uzimati ... ( e -> i )', 
'heiß ' : 'vrelo (vruce)', 
'dabai haben ' : 'imati sa sobom nesto', 
'Gesundheit ' : 'ziv bio, zdrav bio', 
'doch ' : 'potvrdan odgovor na negativno pitanje (jedno od znacnja)', 
'möchten ' : 'zeleti', 
'gar ' : 'uopste', 
'toll ' : 'sjajno, bajno', 
'der Tanz ' : 'ples', 
'tanzen ' : 'plesati', 
'wollen ' : 'zeleti, hteti (situacija)', 
'möchten ' : 'zeleti, hteti (stvari, predmet ... uctiviji oblik)', 
'können ' : 'moci', 
'los sein ' : 'desava se', 
'los ' : 'ajde', 
'jeder ' : 'svako', 
'jede  ' : 'svaka', 
'jedes ' : 'svaki', 
'klar ' : 'jasno', 
'nie ' : 'nikada', 
'noch nie ' : 'nikada nisam ...', 
'erklären ' : 'objasniti', 
'anfangen ' : 'pocinjati (opsti oblik)', 
'starten  ' : 'pocinjati (vazi sa masine, ...)', 
'beginnen ' : 'pocinjati (vazi za odredjeni proces)', 
'fangen ' : 'uhvatiti', 
'üben ' : 'vezbati', 
'über ' : 'iznad', 
'das Team ' : 'tim', 
'die Mannschaft ' : 'tim', 
'singen ' : 'pevati', 
'reiten ' : 'jahati', 
'handstand machen ' : 'stajati na rukama', 
'der Löffel ' : 'kasika', 
'eintragen ' : 'unosenje podataka', 
'tragen ' : 'nositi', 
'das Getränk / -e ' : 'pice', 
'der Unterricht ' : 'predavanje', 
'tun ' : 'ciniti, delovati, raditi (eng. do)', 
'der Tipp / -s ' : 'savet', 
'nur ' : 'samo', 
'das Trinkgeld ' : 'napojnica', 
'die Zeitschrift ' : 'casopis', 
'die Sendung / -en ' : 'emisija', 
'senden ' : 'emitoavti, poslati', 
'das Beispiel ' : 'primer', 
}; 

